### ISSUE TITLE
Include APIs in the catalog

### ISSUE THREAD

**Issue by philipashlock** [GSA/datagov-wptheme#112]
APIs listed in data.json files should naturally be included in the catalog, but this ticket is to make sure that functionality is fully leveraged. 

From Sophie: 

The "Developer" area now has an API list that would be more useful if it were integrated into the main catalog for search. A lefthand nav filter should be added for APIs. Then the manual list on the developer page can be retired and replaced with a link to the filtered list of APIs in the main catalog.

From Nick Muerdter

API catalog/discovery: I think you had also mentioned something that sounded like API discovery. I think the API catalog that will be generated from the agencies' data.json is part of this, but I think we could extend this idea further specifically around APIs. We had talked about this earlier, but one possibility is to have agencies publish more detailed metadata around their APIs (using something like the Swagger JSON specification). Instead of just knowing that an API exists and where it's documentation lives, this would allow us to know all the details about how to call and consume that API programmatically (what parameters does the API take in, what fields are in the response, etc). There are a variety of interesting, automated things we could do if we had this kind of metadata around APIs.

**Comment by gbinal** [comment]
Agreed - It's going to take a while before agencies are thoroughly reporting anywhere close to all of these APIs in their public data listings, so the full API listing will still be needed a while longer, though.

**Comment by JeanneHolm** [comment]
People are split about evenly on whether they search or browse for information.  Often go to the APIs by browsing to it rather than searching for it in the catalog.  This was validated in the usability testing.  We need to keep it in two places--one accessible via browsing and one via searching.  Having some context (such as the developer sites) around the APIs themselves is actually really useful.

**Comment by Raseman** [comment]
The APIs conversation suggests more generic problems we will need solutions for - APIs are just one data type: 1) Challenge 1: how to enable browsing of curated data sets collections in addition to searching (see feature suggestion #61 ("create method of curating data sets") - this as relevant for data sets on particular topics as it is for APIs. The current functionality closest to this is creating Community Categories but these require a data set being added to a topic first, and also there is a bug where the categories from other Communities also appear). 2)  Challenge 2: how to enable integrated lists of data sets that are in the catalog with data sets that have not been added (either because agencies haven't added them, or they are from some other non-federal source, like a state). Right now, for example, about half of the data sets in the Finance Data Directory are not in the Data.gov catalog (http://www.treasury.gov/resource-center/financial-education/Pages/fdd.aspx). Federal data sets will all be added to Data.gov over time, but some data sets may be missing from the catalog for a while so we need a solution for how to present these in a way that makes sense on Data.gov.

**Comment by philipashlock** [comment]
@Raseman Feel free to create new tickets for those if you think they're important. 

The big difference with APIs is that there is already a specific field for them in data.json so we can use the CKAN faceted search feature to let you browse all the APIs that have been added via the data.json harvester. 

@JeanneHolm I agree it's important to have both browse and search functionality, but we get both of those from CKAN, so ultimately we'll be able to rely on that rather than maintain a separate hand edited list. As Gray said, this might take a while, but that's the goal.

**Comment by JeanneHolm** [comment]
When I reference "browsing", I meant that some people do not go to the catalog at all.  They use Data.gov as a web site and browse through the navigation items to find organized content, rather than searching through the catalog.

**Comment by JeanneHolm** [comment]
As of today, we have about 450 APIs and web services on the https://www.data.gov/developers/apis page, but only 62 listed in the catalog under file format: API.  As a result, I think we still need to have these both.  I've added a link in the /developer area to the catalog collection of APIs.
