### ISSUE TITLE
Intelligently update and merge existing entries when importing data.json

### ISSUE THREAD

**Issue by philipashlock** [GSA/datagov-wptheme#114]
Assess impact of updating existing data using data.json

Test what happens to existing metadata in CKAN when new metadata is harvested by data.json. For example, if agency has dataset foo, then agency a's data.json comes in with an update to foo, is foo correctly updated by CKAN?

CKAN will update any data packages with matching identifiers during each harvest process. The issue here is whether identifiers will actual match or whether we should try to do matches based on other fields (like a URL) and whether the update will merge the data on import (eg maintain additional extras) as opposed to just overwriting the entry with the new metadata. 

Referenced to updates based on ID can be seen for the CKAN-CKAN harvester at:
https://github.com/okfn/ckanext-harvest/blob/0f5624822c4fe23e270e4943c268f94238ce6689/ckanext/harvest/harvesters/base.py#L113
https://github.com/okfn/ckanext-harvest/tree/master/ckanext/harvest/harvesters#L370

An alternative approach would be to provide a preview or reporting feature that showed a diff of existing datasets compared to the data.json file that would be used to make updates. With this report, any adjustments could be made at the source of the data.json generation before the harvesting process occurred. This could potentially allow for the initial harvest to be done without the need to conduct any sophisticated merges or updates on the fly during the import process.

**Comment by kvuppala** [comment]
I think alternative approach would be better so that source json file will be in sync with whats in the CKAN catalog, otherwise if the dataset matches based on the name or url, it would be tricky to update the dataset as the unique ids would be different in source json / ckan catalog,  hence the datasets needs to be deleted and inserted with new uniby keeping a snapshop of the deleted entry to merge the dataset metadata fields.

**Comment by kvuppala** [comment]
I think alternative approach would be better so that source json file will be in sync with whats in the CKAN catalog, otherwise if the dataset matches based on the name or url, it would be tricky to update the dataset as the unique ids would be different in source json / ckan catalog,  hence the datasets needs to be deleted and inserted with new unique id in json by keeping a snapshop of the deleted entry to merge the dataset metadata fields.

**Comment by kvuppala** [comment]
I think this can be closed, as we have already finalized the approach on the harvesting.

**Comment by kvuppala** [comment]
We have successfully imported around 11 agency data.json entries, have also migrated the previous topic groups/tags after the data is harvested from agency data.json files.
