### ISSUE TITLE
Successfully harvest data.json files for different organizations into catalog.data.gov

### ISSUE THREAD

**Issue by philipashlock** [GSA/datagov-wptheme#117]

**Comment by JeanneHolm** [comment]
There are two types of organizations referenced here.  The first is to have all the validated agency data.json files harvested and included in catalog.data.gov (see http://data.civicagency.org/offices/ for current status of agency files and validation).  The second is to have the open data files from cities, counties, and states harvested in catalog.data.gov (and add the filter for those categories). In the second case, a second validator will be created that allows for data.json files that are not fully compliant with Project Open Data metadata (since non-federal organizations are not required to be compliant).  Testing is currently underway on these for several cities.

**Comment by dialsunny** [comment]
We now have 2 options to choose from for json harvesting: (1)"Federal" with project open data schema validation and (2) "Non-federal" for cities/counties/states.   

Can this be closed.

**Comment by kvuppala** [comment]
closing this as we have the functionality to harvest both federal/non-federal data.json entries.
