### ISSUE TITLE
 Ability to report problems with datasets

### ISSUE THREAD

**Issue by philipashlock** [GSA/datagov-wptheme#131]
This is a sub-component of #422 

Users should be able to report problems with datasets and metadata about the datasets such as metadata that misclassifies them, datasets with broken links, or any other incorrect or outdated information. 
- [ ] Each dataset page should have a prominent "Report a Problem with this Dataset" button (Needs mockup, see #366)
- [ ] Any dataset that has problem reports should make that easily visible and discoverable on the dataset page (Needs mockup, see #366)
- [x] By default these reports should be public (except for contact information for the reporter
- [ ] These problem reports should automatically be routed to the dataset owner

**Comment by TomRoche** [comment]
@philipashlock: "[allow] users to report datasets that should not be on Data.gov. This can be due to copyright issues, spam or junk, offensive content, etc."

Users should also be able to flag misclassified data, e.g., just-plain-wrong links. E.g., currently (1100 EST 5 Mar 2015) the page for the [2007 Campus Sexual Assault study](http://catalog.data.gov/dataset/campus-sexual-assault-csa-study) links to `http://www.justice.gov/atr/public/criminal/sherman10.xls`, a file containing [Sherman Act Violations Yielding a Corporate Fine of $10 Million or More](http://www.justice.gov/atr/public/criminal/sherman10.xls).

Users should be able to flag these errors. Seeing such a flag could warn others not to use bad links, preventing unnecessary transfers for both her/himself and for data.gov.

Extra credit for auto-alerting the dataset owner regarding the flag: IMHO the user (who in this case is providing a service to the site) should not be required to also find the dataset owner and contact the owner separately.

**Comment by philipashlock** [comment]
Absolutely @TomRoche. I guess we ended up discussing more of the general features in #422, but it's good to capture these details so I've updated the original description. We have a very early beta of this available to test at https://www.data.gov/issue-beta/ but it's not yet integrated with the datasets on catalog.data.gov, but everything you suggested is certainly part of the plan.

**Comment by philipashlock** [comment]
The initial release of this is live with #422 (see https://www.data.gov/meta/announcing-data-gov-help-desk/) but some of the additional features still need to be developed.

**Comment by philipashlock** [comment]
Here's a mockup of the button to report a specific dataset. This should have a URL to the Help Desk form appended with the URL of the dataset on catalog.data.gov

```
<div class="btn-group" style="float:right">
    <a href="https://www.data.gov/issue/?media_url=http%3A%2F%2Fcatalog.data.gov%2Fdataset%2Fnational-stock-number-extract" class="btn btn-info">
    <i class="icon-bullhorn"></i> Report Data Issue </a>
</div>
```

Also note that `#content .toolbar .breadcrumb` has been reduced to a width of `770px`

![screen shot 2015-05-27 at 2 30 07 am](https://cloud.githubusercontent.com/assets/183402/7830220/ac4cf0f4-0418-11e5-909c-442ce1ba7eba.png)

**Comment by nsinai** [comment]
looks promising...!

**Comment by kvuppala** [comment]
change is live and can be seen on every dataset page as per the mockup. 
Example: http://catalog.data.gov/dataset/va-enterprise-data-inventory
