### ISSUE TITLE
It is frustrating to transition from Data.gov to agency sites (for example from the dataset page). Experience of starting search broad and dialing down broke at this transition to the agency site.

### ISSUE THREAD

**Issue by philipashlock** [GSA/datagov-wptheme#139]
Add language to new Introduction to Data.gov tutorial

**Comment by JeanneHolm** [comment]
Will add the language for this to the tutorial.  However, there is some relationship to #317 and #318.  Several users were frustrated because it wasn't clear to them they had transitioned from Data.gov to another agency's site (specifically when going from the dataset page to an agency page linked from it). In some cases, this may have been because the link was to the top of a new search engine on an agency site.

At the same time, those users and others also commented on the irritation with a pop-up that alerted them they were leaving the Data.gov site and going elsewhere.

The discussion about the pop-ups and how they should be implemented is occurring on #317 and #318. The solution for this specific comment is best served by the following:
1.  Update the language on the tutorial
2.  Encourage agencies to link to the specific place on their site where the data resource is, rather than to a higher level spot on the page
3.  Encourage agencies to be clear in the description of what each data resource link is for

**Comment by JeanneHolm** [comment]
Updated the language on the tutorial https://www.data.gov/catalog-help/ and changed the pop-ups to mouseover text that notes the link will go to an external site. #317 #318
