### ISSUE TITLE
The pop up alert on leaving Data.gov page was "painful"

### ISSUE THREAD

**Issue by philipashlock** [GSA/datagov-wptheme#143]
Explain why

**Comment by JeanneHolm** [comment]
Since the text required by OMB to waive this was deleted, a pop up will be required for each link to a non-data.gov app, map, link, or non-federal dataset.

**Comment by ErieMeyer** [comment]
Hey Jeanne -- could you explain more?

What text, and where was it located? And could you share a link to the requirement?

**Comment by JeanneHolm** [comment]
It's a White House requirement http://www.whitehouse.gov/sites/default/files/omb/assets/memoranda_2010/m10-23.pdf 

The OMB text was on all pages showing non-federal data (cities, counties, states, and catalog), and all the Apps, Maps, and Challenges tabs in the topics.

**Comment by ErieMeyer** [comment]
Here's the exact copy Jeanne is referencing for anyone following along:

"External Links. If an agency posts a link that leads to a third-party website or any other location that is not part of an official government domain, the agency should provide an alert to the visitor, such as a statement adjacent to the link or a “pop-up,” explaining that visitors are being directed to a nongovernment website that may have different privacy policies from those of the agency’s official website."

Here's my recommended replacement copy:

"From the lawyers: When you click on links to other websites, you will be leaving Data.gov."

**Comment by cew821** [comment]
Where are the links are we talking about? Data sets in CKAN, or also
possibly links from posts and other items in Wordpress? All of the above?

**Comment by JeanneHolm** [comment]
It is required for links to anything that is not coming from a federal source (remember that there are 225 organizations from which we harvest data in Data.gov http://catalog.data.gov/organization ).  Some of these items in the Data.gov site include the following when they originate from a NON-government entity:
  --Datasets in CKAN
  --Datasets on Cities.Data.gov (and counties and states) (some city sites are managed by a third party)
  --Links to web sites
  --Links to apps
  --Links to challenges
  --Links to maps and visualizations
We currently have language on the catalog, cities, counties, states, apps, maps, and challenges pages on Data.gov that has been approved by OIRA that allows us to, on a page that is all or predominately non-government sources, to provide that at the top clearly so that we don't have to do it for each one.

**Comment by philipashlock** [comment]
I think we might be mixing up two separate tickets here. Ticket #237 is about improving the language used on the disclaimer (used on the CKAN catalog). As I understand it, that disclaimer allows us to avoid the pop-up before going to an external website. 

The ticket here (#143) is about improving the experience of the pop-up (used on the Wordpress content). Unfortunately, I don't know that we currently have any real options to improve this given the policy, but it sounds like the policy might change in the near future. Until then, we could either leave this ticket open or close it with information about the current status and the realities of such policy mandates on user experience.

We have already implemented the pop-up on the Wordpress side. 

The disclaimer text is still in place on the CKAN side, but we can use Ticket #237 to discuss improving the copy or placement of that disclaimer.

**Comment by philipashlock** [comment]
There are still some issues to address as per #274 but otherwise I think this can be closed given the explanation provided above.
