### ISSUE TITLE
Need API usage in real time

### ISSUE THREAD

**Issue by philipashlock** [GSA/datagov-wptheme#148]
Future build

**Comment by philipashlock** [comment]
@gbinal This was also imported from feedback we got in testing last year. Could you provide an update on opportunities agencies have to provide metrics on API usage, eg from api.data.gov

**Comment by gbinal** [comment]
Agencies that use the [api.data.gov service](https://api.data.gov/about/) for their APIs gain access to a robust admin panel for tracking API usage in real time.  They are able to programmatically integrate this elsewhere and could make a front-facing dashboard to publish them, too.  

Any agencies interested in participating should [get in touch](https://api.data.gov/contact/) and we're happy to help get them started (in hours and days, not weeks and months).  

At this point, though, I'm not sure it makes sense to tie adoption of the above to data.gov's roadmap.  I'm closing for now though anyone can re-open if they think otherwise.
