### ISSUE TITLE
The metadata on the catalog page looked like data and was confusing

### ISSUE THREAD

**Issue by philipashlock** [GSA/datagov-wptheme#169]
Verify new look with POD metadata and JSON harvesting

**Comment by ErieMeyer** [comment]
By "verify" do you mean add'l testing? Happy to do quick testing for you whenever the change is on next.

**Comment by philipashlock** [comment]
I'm guessing this refers to there not being clear enough presentation or documentation around all the different metadata fields displayed on each dataset page, but perhaps @JeanneHolm can help fill us in.

**Comment by JeanneHolm** [comment]
Some users thought that the metadata was actually a view of the data itself. The tabular format made them think this. It does say "Additional Info", but labeling or format should be clearer.  Note two examples:

Geospatial data: http://catalog.data.gov/dataset/42fa2675-281e-441b-a277-6f0ac91d319e
Raw data:  http://catalog.data.gov/dataset/grain-transportation-report-table-9 

Suggest replace "Additional Info" with "Information About This Data"

**Comment by ErieMeyer** [comment]
What if we delete "additional info" and the first row ("field" and "value")? My hypothesis that that the users are thinking that "field" and "value" means "fields in the data set" and a "value" rather than sort of a redundant explanation of a table.

Could add in "About"

Illustrated:

Old:

![image](https://f.cloud.github.com/assets/1626026/1603268/871fbc9e-53a7-11e3-8ac6-71bd049dc037.png)

New:

![image](https://f.cloud.github.com/assets/1626026/1603288/c7b1db84-53a7-11e3-84af-7c8f58c69f9d.png)

@mollieru?

**Comment by JeanneHolm** [comment]
That makes sense, although I'd prefer "About this Dataset" as the header.

**Comment by nsinai** [comment]
I like the suggestion @ErieMeyer!  @JeanneHolm, what if the resource is an API?

**Comment by JeanneHolm** [comment]
@nsinai We could say "About this Resource" as an option or the earlier "Additional Information".  Sample API page at http://catalog.data.gov/dataset/recalls-api helps to clarify.

**Comment by ErieMeyer** [comment]
Either seems fine if we can drop that "Field/Value" first row. Possible, @dwcaraway?

**Comment by kvuppala** [comment]
"About this Resource" label goes well with the already existing label "Data and Resources" that is placed above resource URL.

Should be a minor change on the existing catalog.data.gov

**Comment by ErieMeyer** [comment]
In addition to dropping that first row?
