### ISSUE TITLE
Create custom taxonomy for topics

### ISSUE THREAD

**Issue by vz3** [GSA/datagov-wptheme#186]
This will allow posts to use categories as normal. 

How to:
http://wp.smashingmagazine.com/2012/01/04/create-custom-taxonomies-wordpress/

A plugin may be able to do this more quickly.

**Comment by vz3** [comment]
This plugin may be helpful in a pinch:
http://wordpress.org/plugins/types/

**Comment by vz3** [comment]
Looks like we've the Custom Post Type UI plugin we have may do the trick:
http://wordpress.org/plugins/custom-post-type-ui/

**Comment by vz3** [comment]
CPT plugin tested successfully to create "Topics" taxonomy.

Note that this route may mean we use taxonomy-topics.php for the template instead of category.php. Will verify.

Documentation on templating for custom taxonomy:
http://wordpress.org/support/topic/custom-taxonomy-templatearchive

**Comment by kvuppala** [comment]
@vz3 @philipashlock Are we moving away from categories taxonomy for communities, community URLs and links are dependent on the categories such that we retain the same URL of data.gov and this could impact a bit more if we change to new taxonomy and to have same capability.

**Comment by JeanneHolm** [comment]
There is a firm requirement that we retain a top-level URL for the communities so that the community home page can be accessed via something such as Energy.Data.gov and Agriculture.Data.gov.  These names are chosen by the community based on a variety of reasons.

**Comment by kvuppala** [comment]
In the current wordpress solution, the migrated content uses the same URI as it was before in communities.  Also any new posts/pages created follow a specific path (i.e. /energy/XX and /ocean/YY) for metrics, reporting etc.  This is dependent on the categories available.

**Comment by philipashlock** [comment]
We have flexibility to point subdomains like energy.data.gov wherever we want, but I agree that if we made topics/communities act differently than the do now in terms of category structure we would have a different URL on the wordpress side. We could still provide redirects from the old URLs if needed, eg both energy.data.gov and data.gov/energy would redirect to data.gov/topic/energy

Currently I don't think we need to change this, but I do think we need to reevaluate the categories and site structure that depends on them and perhaps create some things as sub-categories. 

Currently there are a whole bunch of extraneous categories that we have to filter out manually, so we should try to clean those up and see if anything might make more sense as a sub-category. For example, Agencies, POCs, Cities, States, etc could all be sub categories of a "Government" or "User Group" category, although ultimately I'm not sure I really understand having Agencies or POCs as groups on data.gov at all. I do think it might make sense to have a category for stuff specifically about the data.gov infrastructure and blog posts coming from the team - This could be the category page that shows all blog posts that aren't coming from a topic/community. Perhaps we could call that category slug "meta"  That name would probably only appear in the URL. Otherwise we could call it Data.gov News or Data.gov Updates. I just think it would be confusing if the category slug was also called datagov such that the url was data.gov/datagov. Alternatively we could call it News, but I think that's more ambiguous. Either one would be better than "Uncategorized" though

**Comment by vz3** [comment]
Changing the taxonomy could be done in a fashion that would not change any URL's.

@JeanneHolm The main reason for exploring this is the extraneous categories that we're filtering out per @philipashlock's comments. If we can delete these categories and if we know that categories will not be needed within posts (i.e. the energy community won't ever have the requirement to allow users to see all posts on "renewable" or "solar"), then this is moot. I am concerned that that functionality will be needed in the short to medium term.

**Comment by dano-reisys** [comment]
@vz3 , we've used CPT UI in order to generate custom post/taxonomy code that we keep in one of our custom modules... but it is also possible to keep that code in functions.php (otherwise CPT stores custom post types/taxonomies somewhere in the database)

**Comment by vz3** [comment]
Short term solution: Delete unused categories, create new subcategory heirarchial taxonomy in future.

Closing issue.
