### ISSUE TITLE
Links in Posts are stripped out when they appear on main page

### ISSUE THREAD

**Issue by cew821** [GSA/datagov-wptheme#191]
When I create a post labeled as an "update," the links in that post don't appear in the summary on the main topic pages. It would be better if the links stayed in this summary section, since many news updates are simply links to new data resources.

No links:
![nolinks](https://f.cloud.github.com/assets/1237498/1725157/fab9fcf4-627b-11e3-964f-84c4b7391145.png)

Links appear when you view article:
![nolinks1](https://f.cloud.github.com/assets/1237498/1725183/544d0f2c-627c-11e3-836f-a9f5d88f9f65.png)

**Comment by philipashlock** [comment]
The best way to address this is by specifying an excerpt for each post by identifying where the summary ends with the  tag:
http://en.support.wordpress.com/splitting-content/more-tag/

Support for this was added by this commit:
https://github.com/GSA/data.gov/commit/4ef218e1718832815e5286ec1f9216c4ecc55e35

The only issue with this right now is that we can't customize the text of the link because of a conflict with the Custom Post View Generator plugin.

**Comment by kvuppala** [comment]
@philipashlock should we try to resolve the conflict, or do you think we should move away from Custom Post View Generator?  Metrics depend on the this plugin, it might be worth to resolve the conflict.

**Comment by dialsunny** [comment]
This should be resolved now.

**Comment by philipashlock** [comment]
It looks like this still needs to be applied to the frontpage - https://github.com/GSA/data.gov/blob/master/themes/roots-nextdatagov/templates/content-excerpts.php#L50

**Comment by dialsunny** [comment]
It has now been applied to homepage as well.
