### ISSUE TITLE
Drop "agencies" community

### ISSUE THREAD

**Issue by ErieMeyer** [GSA/datagov-wptheme#225]
Suggestion: We could/should drop the "agencies" community for the following reasons:
1. Content is focused on government users rather than external users, contrary to the focus of the site
2. Content _for_ gov folks should be housed at howto.gov to make sure it's not missed by people who are looking for it
3. Another place to share this stuff if it _is_ appropriate for external users would be in the open data stack exchange to get additional feedback. Ex: "This is is what we do. Do you think it's a best practice?" to take advantage of the collective insight of the community.

For reference

Link :http://next.data.gov/agencies/

Screenshot: 
![image](https://f.cloud.github.com/assets/1626026/1738130/f7a6dd80-637e-11e3-9819-b5d9e8a13676.png)

**Comment by MarionRoyal** [comment]
They may not be external users, but they are our customers, especially if
we try to go for a shared cost model in FY15.  We need to continue reaching
out to the agencies, encouraging them to publish, and making it as easy as
possible.
Why don't we let it ride and see what the traffic looks like.

Marion A. Royal
202.302.4634

Sent from PDA

On Dec 12, 2013, at 5:45 PM, Erie Meyer notifications@github.com wrote:

Suggestion: We could/should drop the "agencies" community for the following
reasons:

   1.

   Content is focused on government users rather than external users,
   contrary to the focus of the site
   2.

   Content _for_ gov folks should be housed at howto.gov to make sure it's
   not missed by people who are looking for it
   3.

   Another place to share this stuff if it _is_ appropriate for external
   users would be in the open data stack exchange to get additional feedback.
   Ex: "This is is what we do. Do you think it's a best practice?" to take
   advantage of the collective insight of the community.

For reference

Link :http://next.data.gov/agencies/

Screenshot:
[image: image]https://f.cloud.github.com/assets/1626026/1738130/f7a6dd80-637e-11e3-9819-b5d9e8a13676.png

—
Reply to this email directly or view it on
GitHubhttps://github.com/GSA/data.gov/issues/225
.

**Comment by MarionRoyal** [comment]
A follow up thought is that after the new year, we might consider using our
theme to build a simple front end to inventory.data.gov.  We could then
move the agency community over to that site.

Marion A. Royal
202.302.4634

Sent from PDA

On Dec 12, 2013, at 6:34 PM, Marion Royal - XI marion.royal@gsa.gov wrote:

They may not be external users, but they are our customers, especially if
we try to go for a shared cost model in FY15.  We need to continue reaching
out to the agencies, encouraging them to publish, and making it as easy as
possible.
Why don't we let it ride and see what the traffic looks like.

Marion A. Royal
202.302.4634

Sent from PDA

On Dec 12, 2013, at 5:45 PM, Erie Meyer notifications@github.com wrote:

Suggestion: We could/should drop the "agencies" community for the following
reasons:

   1.

   Content is focused on government users rather than external users,
   contrary to the focus of the site
   2.

   Content _for_ gov folks should be housed at howto.gov to make sure it's
   not missed by people who are looking for it
   3.

   Another place to share this stuff if it _is_ appropriate for external
   users would be in the open data stack exchange to get additional feedback.
   Ex: "This is is what we do. Do you think it's a best practice?" to take
   advantage of the collective insight of the community.

For reference

Link :http://next.data.gov/agencies/

Screenshot:
[image: image]https://f.cloud.github.com/assets/1626026/1738130/f7a6dd80-637e-11e3-9819-b5d9e8a13676.png

—
Reply to this email directly or view it on
GitHubhttps://github.com/GSA/data.gov/issues/225
.

**Comment by ErieMeyer** [comment]
Hey Marion!

Totally hear you that these three are the goals for agency engagement:
- Reaching out to the agencies
- Encouraging them to publish, and
- Making it as easy as possible to do so

But I'm seeing that there are only three posts on the page right now, and they don't seem to address any of these goals. Which is super understandable! I know lots of other things are going on. I know these are really important to the team, which is why I worry about rushing to launch this page without addressing/testing how well this content could meet those goals.

My hypothesis is that the energy spent making new content to address these could be invested in continuing/expanding the work Jeanne is doing in building relationships with these groups, setting a larger editorial strategy, and strengthening the feedback loop between agencies.

Will connect offline with the templates we discussed earlier this week!

**Comment by MarionRoyal** [comment]
_It can scarcely be denied that the supreme goal of all theory is to make
the irreducible basic elements as simple and as few as possible without
having to surrender the adequate representation of a single datum of
experience._

_I think that was Einsteins way of saying that things should be as simple
as possible, but no simpler._

_We may be approaching that level at next.data.gov http://next.data.gov_

_marion_

Marion A. Royal
202.302.4634

Sent from PDA

On Dec 12, 2013, at 7:03 PM, Erie Meyer notifications@github.com wrote:

Hey Marion!

Totally hear you that these three are the goals for agency engagement:
- Reaching out to the agencies
- Encouraging them to publish, and
- Making it as easy as possible to do so

But I'm seeing that there are only three posts on the page right now, and
they don't seem to address any of these goals. Which is super
understandable! I know lots of other things are going on. I know these are
really important to the team, which is why I worry about rushing to launch
this page without addressing/testing how well this content could meet those
goals.

My hypothesis is that the energy spent making new content to address these
could be invested in continuing/expanding the work Jeanne is doing in
building relationships with these groups, setting a larger editorial
strategy, and strengthening the feedback loop between agencies.

Will connect offline with the templates we discussed earlier this week!

—
Reply to this email directly or view it on
GitHubhttps://github.com/GSA/data.gov/issues/225#issuecomment-30474986
.

**Comment by nsinai** [comment]
Hi guys!  Sorry for the late entrance. What’s the plan to close this out?  I'd suggest we drop for now, unless we have compelling reason to keep.  We can always add back if necessary.  Thanks!

**Comment by MarionRoyal** [comment]
We hadn't really planned to close it out.  We might move it to
inventory.data.gov in the future.
If there is a strong feeling from OSTP to remove it, we will of course.
 But my feeling from the team consensus is that it adds value to the new
Datagov.

Marion A. Royal
202.302.4634

Sent from PDA

On Dec 13, 2013, at 2:41 PM, Nick Sinai notifications@github.com wrote:

Hi guys! Sorry for the late entrance. What’s the plan to close this out?
I'd suggest we drop for now, unless we have compelling reason to keep. We
can always add back if necessary. Thanks!

—
Reply to this email directly or view it on
GitHubhttps://github.com/GSA/data.gov/issues/225#issuecomment-30537386
.

**Comment by philipashlock** [comment]
I think the short term solution for this is that there will still be an entity called "Agencies" but that it won't be displayed on the front page, but instead through a link in the footer titled "Data Publishers." Long term I do think it makes sense to consider if there's a more appropriate place for this such as inventory.data.gov, howto.gov, Project Open Data, or something else.

**Comment by cew821** [comment]
Seems reasonable. I'm not opposed to having it, but it's not clear to me
who the intended audience is (and who the intended content contributors
are). Given the lack of relevant content in the community now, it makes
sense to 'hide' it.

**Comment by MarionRoyal** [comment]
That sounds like a good approach to me.

Marion A. Royal
202.302.4634

Sent from PDA

On Dec 13, 2013, at 3:56 PM, Charles Worthignton notifications@github.com
wrote:

Seems reasonable. I'm not opposed to having it, but it's not clear to me
who the intended audience is (and who the intended content contributors
are). Given the lack of relevant content in the community now, it makes
sense to 'hide' it.

On Fri, Dec 13, 2013 at 3:54 PM, Philip Ashlock
notifications@github.comwrote:

> I think the short term solution for this is that there will still be an
> entity called "Agencies" but that it won't be displayed on the front
> page,
> but instead through a link in the footer titled "Data Publishers." Long
> term I do think it makes sense to consider if there's a more appropriate
> place for this such as inventory.data.gov, howto.gov, Project Open Data,
> or something else.
> 
> —
> Reply to this email directly or view it on GitHub<
> https://github.com/GSA/data.gov/issues/225#issuecomment-30542795>
> .

—
Reply to this email directly or view it on
GitHubhttps://github.com/GSA/data.gov/issues/225#issuecomment-30542947
.

**Comment by JeanneHolm** [comment]
Agencies community content was moved to the Data Publishers page at http://next.data.gov/agencies/.  This is accessible from the site footer.
