### ISSUE TITLE
topic page goes into infinite loop

### ISSUE THREAD

**Issue by kvuppala** [GSA/datagov-wptheme#230]
when a post is associated to "Topic Intro" and a category (ex: food), the food category page goes into infinite redirect, and also the admin posts page goes into infinite loop.

Must fix for release.

**Comment by kvuppala** [comment]
Screenshot attached below.

![post_topic_intro_error](https://f.cloud.github.com/assets/1738764/1748791/e6a919f0-64df-11e3-9921-69784cad6467.png)

**Comment by philipashlock** [comment]
I'm unable to recreate this bug on my local environment or my staging server. 

Here's the energy topic page which includes intro text:
http://datagov-staging.civicagency.org/energy/

The actual Topic Introduction page is at this URL but it will redirect you to the topic page:
http://datagov-staging.civicagency.org/energy/page/energy-welcome

The logic to handle the redirect is at https://github.com/GSA/data.gov/blob/dev/themes/roots-nextdatagov/lib/custom.php#L49

Perhaps you're trying to specify a Post as a Topic Introduction rather than a Page? We should probably update the query in category.php to filter out for anything set as Topic Introduction (featured->browse custom taxonomy) in case somebody accidentally sets a post as a Topic Introduction.  This was part of the reason why I was trying to have these custom taxonomies only for Pages rather than for Posts and Pages.

**Comment by kvuppala** [comment]
Yes issue happens when a post is marked as intro ,  if we can filter the posts user error can avoided for now.  I agree that we need to did a way to restrict them by page / post

**Comment by philipashlock** [comment]
This should be fixed by 5298737b445a0e1b72c1d1442c95c691f696cb03
