### ISSUE TITLE
Limit in number of "highlight" posts for a community

### ISSUE THREAD

**Issue by dialsunny** [GSA/datagov-wptheme#231]
There seems to be some limit on number of highlight posts that could appear in /highlights page for a particular community.

For example, Agriculture has 9 posts marked that are "highlighted" but only 5 show-up in http://next.data.gov/highlights

**Comment by philipashlock** [comment]
Yeah, it's just a normal limit set in the WP_Query argument. 

We can change this to 10 for now, but right now I don't think there should be more than 10 highlights per topic if the community managers are focusing on impact and quality over quantity. I would really expect this to be more like 5, but I think we'll need to discuss in more detail how the highlights are being curated because it seems like there might be two separate needs, one for these major highlights that don't change often and something else to feature more serialized content. 

On the highlights page the limit is set here:
https://github.com/GSA/data.gov/blob/dev/themes/roots-nextdatagov/taxonomy-featured-highlights.php#L45

Edit: removed erroneous link to query limit on category page, which actually is [set to only limit to 1 right now](https://github.com/GSA/data.gov/blob/dev/themes/roots-nextdatagov/templates/content-highlights.php#L20). This is used for the frontpage too, so lets not change this until we're prepared to handle multiple highlights on those pages.

**Comment by dialsunny** [comment]
sounds good. We can also add a small note of reference to state that max 10 posts can be Highlighted. 

Additionally,
If users try to add beyond limit, we can either throw an error message OR move those extra highlights as standard News/Updates in the community. That way, extra highlights won't get lost and be displayed somewhere.

**Comment by kvuppala** [comment]
changed the highlights limit to 10

**Comment by JeanneHolm** [comment]
We would likely want to expand this in the future as over time the number of highlights will grow and people may want to refer to the entire collection of highlights over time. Users often ask about a previously featured piece of content and want to be able to see the archive.

**Comment by cew821** [comment]
I agree that having a way to view all the "highlights" within a topic is a useful feature. Assuming people use this as a way to list their "featured" or "most important" datasets, I would think we would want to be able to show all highlights, not just the most recently posted.

If highlights are not supposed to = "featured datasets" then I feel less strongly about this.

**Comment by JeanneHolm** [comment]
Highlights = featured datasets.  There is one type of highlight that shows the dataset in action showcasing a company for example, but it is really an expanded version of a featured dataset.

**Comment by cew821** [comment]
That's what I thought. So yes, I would think there should be a way to see all the featured datasets on (or linked from) each topic page.

In my head "Highlights" = "the most important datasets related to this topic" while "Updates" = "Stories, news releases, newly-released datasets, blogs about cool uses of data, etc." Maybe this is something that could be clarified in a style guide (cc/ @ErieMeyer )

**Comment by Raseman** [comment]
Whatever length we decide, we should introduce a range that topics need to stay between for what is posted so they don't look too uneven.

**Comment by JeanneHolm** [comment]
We can put a word limit on the field.

**Comment by Raseman** [comment]
Aren't we talking a # of posts limit, rather than a word limit here?

---

Sophie Raseman
+1 (203) 500-7090
raseman@gmail.com

**Comment by JeanneHolm** [comment]
In summary, we should add a word limit on the field to keep balance, add "More highlights" to be able to refer to earlier highlights on a separate page that lists them all, and perhaps explore the ability to view multiple highlights on a topic.

**Comment by dialsunny** [comment]
On a topic landing page, only the most recent highlight is now being shown. "More Highlights" link is also shown which links to a page showing all highlights for the topic.
