### ISSUE TITLE
Text explaining Data.gov catalog entries

### ISSUE THREAD

**Issue by JeanneHolm** [GSA/datagov-wptheme#237]
OMB/OIRA requires that if we provide a catalog that federates to both federal and non-federal sources, the following text needs to be at the top of the catalog page: 

Note that only datasets marked as "Federal" are subject to the U.S. Federal Government and Data.gov's Data Policy. Non-federal participants (e.g., universities, organizations, and tribal, state, and local governments) maintain their own data policies. It is important that users understand the data policies of participating entities in order to best utilize these datasets. A description of this catalog and information about the datasets presented and associated metrics is available here

**Comment by ErieMeyer** [comment]
A question and a note:

Q: Could you share where that exact text came from? In my experience, OMB/OIRA is open to editing any content they require as long as it gets the point across.

Note: Linking "here" instead of the word(s) you're referring to is an accessibility barrier. By linking to the word "here" when a screen reader browses down a page, it just reads "here" to the user rather than what the link is actually going to.

Would suggest switching this to:

"Note: Different types of data publishers (Federal, state, organizations, etc.) also have different data policies."

**Comment by philipashlock** [comment]
We can close this right?

**Comment by ErieMeyer** [comment]
Yes!
