### ISSUE TITLE
Creation of highlights page

### ISSUE THREAD

**Issue by JeanneHolm** [GSA/datagov-wptheme#240]
The highlights page should point to a few featured highlights in each topic.  A WordPress option should be included that allows the site manager to select some of the topic highlights.  Suggestion is to add another checkbox for the Featured Content options like "Featured on Highlights page" and to check that for anything to show up on the Highlights page.

**Comment by dialsunny** [comment]
Here is the approach we will take on this item:

1.On Main Highlights page(https://www.data.gov/highlights/), show 2 latest posts under each topic(instead of all highlights). 
2. Then, show a link as "More Highlights" under each topic(which has >2 highlights) to direct to the topic highlight page showing all highlights for the topic(e.g. https://www.data.gov/food/highlights)

**Comment by dialsunny** [comment]
Also related to https://github.com/GSA/data.gov/issues/360

**Comment by dialsunny** [comment]
The above change has been applied.
