### ISSUE TITLE
Post authorship quirks

### ISSUE THREAD

**Issue by ErieMeyer** [GSA/datagov-wptheme#245]
![image](https://f.cloud.github.com/assets/1626026/1841687/4db0ba9c-74ab-11e3-9451-9b56fdc4b47c.png)

Hi!

Make sense to drop the dynamic "author" listing for posts if we're manually entering them into the post body themselves?

**Comment by JeanneHolm** [comment]
Could you clarify? Do you want to remove the poster's name "Sophie" when they are reposting a blog or content from another person? I think we either have it always on or always off. The only way to avoid it, I think, is to create a user account for each cross-posted user ("Michael" here) and then to modify the post to be under their name as the poster.

**Comment by ErieMeyer** [comment]
I think your suggestion is on point, if you think that will be a reasonable workflow for you guys. I'm agnostic on the solution, just as long as we don't have double authors on posts. Thank you!

**Comment by Raseman** [comment]
As a very short term solution, I would recommend that we call the author by the real author names, rather than the poster name. As a backup, we could change them all to Admin. 

As a long term solution, I think we should no longer have duplicated blog posts from other sites, and instead we should have a common format for adding just the title, real authors, date, and teaser intro text, as well as perhaps an image.

**Comment by Raseman** [comment]
We should have a field for author names - not just create fake poster names - this way you can actually tell who posted the item (it just wouldn't be visible)

**Comment by philipashlock** [comment]
Here are two proposals: 

1) Use a custom author byline for all posts. Because these bylines can often be quite long and include multiple authors it wouldn't really be feasible to list this in the main heading of posts, at least not when displayed as a list/feed. 

2) Use a custom author byline when needed and use the wordpress author when it makes sense. Since the wordpress author is just one name it's feasible to include it in the header as we have now. It also acts as a link to the archives of what's been written by that author. The main disadvantage of this is inconsistency since some headings would have the author and some wouldn't. 

I'm generally in favor of option 1

**Comment by Raseman** [comment]
See my issue #250 - we need two separate templates -one for a "native" post in Data.gov that is originally authored in Data.gov, and one that is a template for linking to external blog posts. We should at a minimum have separate structured fields for agency author, staff author #1 name, staff author #1 titles (etc. to accommodate multiple authors), date of original publication (NOT published date on data.gov), link to original post, and a teaser intro paragraph. This way we can play around with the design of how the agency and staff authors are displayed and it will be consistent.

The identity of the individual who creates and publishes the post in Wordpress should not be displayed ever on the site. Displayed author should always be separate, whether for a "Data.gov native" blog post or a post referencing an external blog post.

**Comment by JeanneHolm** [comment]
Sounds like the last two comments make sense.  Once we have a solution built, we can manage past posts, at least for the issues where it was clearly posted by one person and written by another.

**Comment by philipashlock** [comment]
By agency author, do you just mean the name of the agency that represents the source of the post? Is there any reason that the agency, author(s), and author titles(s) each need to be separate fields or could we just use one free form field where the complete authorship byline could be written in whole? 

Is there any reason to not just reuse the native published date field in wordpress for the original publication date? It's editable. One reason to not use that is that it generally controls the ordering of posts, so if we wanted something that was originally published a while ago to show up in the top of the feed then we couldn't reliably do both with the native wordpress date field.

**Comment by Raseman** [comment]
Yes I do mean the agency publishing the post or press release when I say
"agency author." (Press releases are unauthored, so this is particularly
important for them.)

Here's a crack at the argument for capturing separate structured input on
the blog posts/press releases we link to for the updates section:
1) Most importantly in short term - It will enforce consistency by users in
formatting. Otherwise users will include different information (e.g., some
will leave out agency, author titles, etc.) and will use different
formatting (e.g., some will input "by" and others will not).
2) It will allow us to easily change how the formatting is displayed - both
now as we are testing different designs and in the future without needing
to manually edit the posts.
3) It will enable new features in the future - such as displaying or
allowing search across all blog posts by one agency, one author, etc. For
example, in the future we may want to display all blog posts or press
releases by one agency next to the data sets by an agency when a user
searches in the data catalog nav just for data sets by that agency
4) Finally: It is in the spirit of data.gov to capture this content in a
machine readable format that can be released in structured form to the
public! :-)

---

Sophie Raseman
+1 (203) 500-7090
raseman@gmail.com

**Comment by philipashlock** [comment]
I agree with your arguments in theory, but in practice I'm not sure we can actually do this without a lot of inconsistency and headaches. 

The problem with using structured fields here is that I'm not sure there's a consistent enough structure for the kind of large bylines you're talking about. The main contributing factor is that often there are multiple authors from multiple agencies and there's not an easy way for us to provide an unpredictable number of these fields. (note to self: if we do this we'll want [repeaters](http://www.advancedcustomfields.com/add-ons/repeater-field/))

As for your first point, we can at least provide an example in the field itself, but ultimately we'll always need to enforce editorial oversight and quality control over each post.

As for the structured data, we can always use free form tags to make it easier to filter by things like agency

**Comment by kvuppala** [comment]
Already addressed by removing the author name on the posts, closing this but will have a separate issue for longer term solution.
