### ISSUE TITLE
Bug - selecting a nav item in the catalog should not send you to the top of the page on refresh

### ISSUE THREAD

**Issue by Raseman** [GSA/datagov-wptheme#256]
When you select a filter on the lefthand nav of the catalog page, you are sent back to the top of the page when the page refreshes. This makes it difficult to find where you were since there are so many different filter categories.

**Comment by dialsunny** [comment]
The issue has been resolved.

**Comment by philipashlock** [comment]
For now this was addressed by using a named anchor so that the page reloads and attempts to automatically scroll to the part of the page where the clicked "Show More" link is. This is definitely an improvement over the page just loading and leaving you at the top of the page, but it's still not as seamless as if it was done all client-side (eg via AJAX) so that there is no full page reload or movement of the page whatsoever. Aside from just being a little slow and jittery with the whole page reload, the current solution doesn't always position the page quite right, perhaps because there can be some delayed page loading that shifts content down after the browser has already positioned the page at the named anchor. The current fix has addressed the problem as it was originally described so I'll close it, but will add another ticket for a more seamless client-side solution to this.
