### ISSUE TITLE
Clean Up Format Tags via Standardizing & Separating Multiple Formats

### ISSUE THREAD

**Issue by Raseman** [GSA/datagov-wptheme#258]
Currently there are a couple major problems for the format lefthand nav filter for the data catalog:
1) The terms are not standardized (e.g., "csv" / "csv text" / "csv text file" are all used)
2) Multiple formats in a list are treated as a unique format (string?) (e.g., "csv/text, pdf")

This needs to be cleaned up, but if it can't be cleaned up in the source catalogs immediately, perhaps one could search the full text of the tags for "csv OR text OR ascii" and filter by that search instead)

**Comment by Raseman** [comment]
Just noticed that there appear to be standardized tags on at least some of the the catalog entries themselves that launch the downloads - perhaps those could be used to filter.

![screen shot 2014-01-03 at 3 28 21 pm](https://f.cloud.github.com/assets/3143170/1843350/4128ccaa-74cf-11e3-8b5e-ece3e483684b.png)

**Comment by JeanneHolm** [comment]
Agree on this @Raseman. We will be addressing many of the catalog navigation issues with build 2.6.

**Comment by JeanneHolm** [comment]
@Raseman We are still in agreement on this, but need to move this and some other CKAN-related items to Milestone 2.7 in June.

**Comment by philipashlock** [comment]
This is already happening naturally through the process of implementing the Project Open Data schema which is based on standardized mimetypes, but I think we can still do more targeting to clean up format types that are incorrect or inconsistent. Since the main problem here is primarily being addressed already through the new data.json files, I think we can close this issue. I will however open new issues for specific strategies to help improve the process moving forward:

#55 (Validate File Formats)
#409 (Formats search filter should be ordered by most common occurrence)
