### ISSUE TITLE
Y U NO USE API?

### ISSUE THREAD

**Issue by benbalter** [GSA/datagov-wptheme#27]
The site looks absolutely :sparkles:. Taking a quick peak at the code, there's a bit of low hanging fruit that could really make things come together a lot more smoothly:
- Instead of `get_template_part('header')`, use `get_header()`, instead of `get_template_part('footer')`, use `get_footer()`. This fires API hooks (in addition to including the templates) and allows third-party plugins to properly integrate with your theme.
- Instead of `<script src="<?php echo get_bloginfo('template_directory'); ?>/js/v1.js"></script>`, use [`wp_enqueue_script`](http://codex.wordpress.org/Function_Reference/wp_enqueue_script). This manages dependencies and versions for you, and allows you to integrate with third-party plugins such as allowing W3TC (which you're using) to concat and minify scripts.
- Instead of `<link rel="stylesheet" href="<?php echo get_bloginfo('template_directory'); ?>/stylesheets/base.css">
  ` use [`wp_enqueue_style`](http://codex.wordpress.org/Function_Reference/wp_enqueue_style). Same rationale as `wp_enqueue_script`
- Use `wp_title` for the page title, rather than hard-coding the site name. This will allow the site title to be dynamic from page to page.
- Use `body_class` to append the body class dynamically
- You can use the child theme API to DRY up the template and make upstream updates to the base theme much easier.

The theme looks great, but, there are a handful of WordPress conventions that it seems to deviate from (e.g., putting `<html>` in `index.php`, not `header.php`). These norms are generally best practices, which will cause the project less pain in the long run, but are also what most WordPress developers have come to expect, increasing the friction for community members to contribute. In general, [the default theme](https://github.com/WordPress/WordPress/tree/master/wp-content/themes/twentythirteen) is well documented and a great template.

Again, awesome, awesome stuff. Can't wait to see how this evolves.

:us: :lipstick: :tada: :confetti_ball: : :baby: :footprints: 

/cc @nacin

**Comment by nacin** [comment]
An additional note on header and footer:
- Technically, `get_header()` and `get_template_part('header')` are synonymous under the hood. But `get_header()` is more standard and also fires an additional action hook. The same goes for the footer.
- `wp_head()` and `wp_footer()` go just before `</head>` and `</body>` respectively. These are used by plugins and the script/ style enqueues and such. ~~(Note that @benbalter accidentally called `get_header()` `wp_head()` in his post.)~~
- Rather than think of `header.php` as your `<head>` and `footer.php` as your footer specifically, think of them as the top and bottom of your page. This usually means `<html>` (and doctype), through `<head>` (including `wp_head()`), into the body, and after the site's header and navigation. The footer usually includes the footer through `</html>`. The pattern you use isn't "wrong" but you may find it difficult to maintain.

**Comment by georgestephanis** [comment]
Also, instead of including Masonry in the theme, you can much more easily use the version already provided by core since [r20060](http://core.trac.wordpress.org/changeset/20060)

I'll have a pull request together shortly for lots of these changes.

EDIT: Here y'go: https://github.com/GSA/datagov-design/pull/30

**Comment by JeanneHolm** [comment]
Thanks, pull request 30 accepted.
