### ISSUE TITLE
Links from open source section don't work

### ISSUE THREAD

**Issue by ErieMeyer** [GSA/datagov-wptheme#272]
Hey!

When I mouse over links it shows where they should land, but when I click on them, you don't actually go anywhere: http://next.data.gov/developers/open-source

Click on the first item -- 3D-Repository -- to see what I mean.

I'm using chrome on a mac.

**Comment by JeanneHolm** [comment]
I think there's a better way to present this content as well.  @gbinal The underlying pages on Github are not returning content correctly in generating this page, can we pull the content in another way?

**Comment by gbinal** [comment]
+emails, since it looks like github is suffering some
downtimehttps://status.github.comright now (I'm seeing a unicorn).

A couple things at issue here.  Main one is that it's an iframe in the page
so links load in the iframe.  I'm editing this project right now so that
the hyperlinks open in a new tab, which should resolve this.

Note that sometimes you may get a message about hitting the API too many
times but that message is specific to your IP address so for 99.5% of the
visitors, it'll never come into play.

Gray

---

c - 205.541.2245
Sr. API Strategist
Digital Services Innovation Center - GSA
- HowTo.gov/api
- US Government APIs
  listservehttps://groups.google.com/forum/?fromgroups#!forum/us-government-apis

**Comment by philipashlock** [comment]
We should avoid iframes as much as possible, so for now I've just gone ahead and made it a link. It was actually a direct link to this page in the navigation earlier, but I saw that some content on this page with the iframe had already been created so I figured I'd continue using it.

**Comment by gbinal** [comment]
Sounds good.

G
