### ISSUE TITLE
Catalog API - package_list fails

### ISSUE THREAD

**Issue by rossjones** [GSA/datagov-wptheme#295]
When trying to access package_list

```
curl http://catalog.data.gov/api/3/action/package_list
```

it takes approx 2 minutes to return and then gives

```
HTTP/1.1 503 Service Unavailable
Server: Apache
ETag: "9fbbc13f2e8a5463b13d21c309cf6788:1389570036"
Last-Modified: Sun, 12 Jan 2014 23:40:36 GMT
Content-Type: text/html
Date: Tue, 14 Jan 2014 14:09:22 GMT
Connection: keep-alive
Cache-Control: max-age=0, no-cache, no-store
```

**Comment by TMLutas** [comment]
I can confirm that this is still going on. Trying to access this via wget -r --content-on-error http://catalog.data.gov/api/3/action/package_list yields further information two files are returned, the shorter of which states "Bad request - Action name not known: package_listcd". Kudos to Canadian friend on my blog PenGun who spotted this variant for me.

**Comment by JeanneHolm** [comment]
Thanks for the note. Seems to be an issue that may take a while to resolve with our CKAN partners. In the meantime, we'll get something up for a fix.  @philipashlock will have some more information shortly.

**Comment by philipashlock** [comment]
Thanks for reporting. By default this API call doesn't have any limit on it so it is attempting to return all records on catalog.data.gov and is timing out before the request can be completed. Unfortunately this call also does not seem to be accepting the parameter to limit the response. Until this is fixed, I would recommend that you instead use `package_search` (see [documentation](http://docs.ckan.org/en/latest/api/index.html#ckan.logic.action.get.package_search)) and page through the responses with smaller payloads using the `rows` and `start` parameters, eg `http://catalog.data.gov/api/3/action/package_search?rows=10&start=1`

_I've updated this comment to recommend `package_search` instead of `current_package_list_with_resources` since it also includes a count of the number of results returned to make pagination easier._

**Comment by TMLutas** [comment]
I got the response and it's working well enough as a substitute for now. The only thing missing is a way to programmatically get the total number of  datasets, or did I just miss that in the docs?

**Comment by kvuppala** [comment]
in the package_search api call response, with in the "result" there is a count indicating the total number of datasets.

"result": {
    "count": 89456,
    "search_facets": { },
..

**Comment by kvuppala** [comment]
http://catalog.data.gov/api/action/package_list now is redirected to http://catalog.data.gov/api/action/package_search, it allows the client apis to go through the api to get to the whole data.

Look at the package_search api @ http://docs.ckan.org/en/latest/

**Comment by rebeccawilliams** [comment]
Re-opening this issue, since there is [value](https://opendata.stackexchange.com/questions/4240/how-do-i-get-a-full-list-of-datasets-available-on-data-gov-using-the-ckan-api?atw=1) in getting package_list to work properly (w limit and offset?) or determining a better workaround to download _all the metadata_.

**Comment by siccovansas** [comment]
I would really like to see package_list work!

**Comment by jsfenfen** [comment]
Hey @kvuppala, noticed that the redirect you applied in 2014 for http://catalog.data.gov/api/action/package_list  to http://catalog.data.gov/api/action/package_search seems outdated as there's now a '3' in the url, i.e. it's now http://catalog.data.gov/api/3/action/package_list and the response is an akamai error. But it would be really useful if this worked as expected!

**Comment by kvuppala** [comment]
@jsfenfen now the URLs are working as expected.  thank you for flagging the issue.
