### ISSUE TITLE
Standardize agency open data lead email addresses

### ISSUE THREAD

**Issue by JeanneHolm** [GSA/datagov-wptheme#304]
Via @lukefretwell Tip: standardize agency point of contact emails (e.g., opendata@agencyname.gov). Like /open or /developers.

https://twitter.com/lukefretwell/statuses/428316447735951360

**Comment by JeanneHolm** [comment]
Counter-suggestion: create an online way to initiate a request or email to the current agency lead(s) for each agency.  We are currently combining several lists of open data experts and leads to have an up-to-date listing.

**Comment by rebeccawilliams** [comment]
@lukefretwell, A few thoughts: I think this might be a better coordinated by [Project Open Data](https://project-open-data.github.io/schema/) and should be suggested there. Also, encouraging a non-specific contact name might be counter productive to assigning responsibility and generating prompt responses.

**Comment by JeanneHolm** [comment]
Agreed on Project Open Data--we are combining lists with them.  And the links for these would, in general, be to a specific person.

**Comment by rebeccawilliams** [comment]
Cross-tagging the related #174 here too (points of contact for Topic areas).

**Comment by lukefretwell** [comment]
Thought on standardizing the email was that it would be intuitive/easy for citizens to send a request rather than having to hunt down a specific person. So data@agencyname.gov seems useful. Having an associated contact is also great, but from an operations perspective, always best to standardize so you don't have to keep updating when someone else leaves. Speaking from personal experience, I've had personal contacts and sent inquiries and it hasn't helped much. ;-)

I'd also suggest Data.gov using RecordTrac for this: http://records.oaklandnet.com/new

That way you eliminate the black hole issue: http://records.oaklandnet.com/requests?closed=false&sort_column=id&sort_direction=desc&min_request_date=&max_request_date=&department=&page_number=1&search_term=

**Comment by rebeccawilliams** [comment]
@lukefretwell I reiterate that I think the standardized email address is an issue to file with the collaborative open data policy, [Project Open Data](https://github.com/project-open-data/project-open-data.github.io/issues). Specifically I think this is a comment on notes associated with the [Contact Email metadata field](https://project-open-data.github.io/schema/). As of now each agency provides their own preferred contact email address, which Data.gov harvests (but does not modify or intercept). Is it okay if I port this ask over there? 

To your 2nd point, see: #422.

**Comment by philipashlock** [comment]
@lukefretwell we'll definitely do our best to check to see if email addresses are current for each dataset, but as far as providing guidance or requirements about standardized addresses for each agency, I think that would be best to cover as part of @project-open-data. Mind filing this there instead? https://github.com/project-open-data/project-open-data.github.io/issues

Going to close here for now, but happy to see this resolved somehow.
