### ISSUE TITLE
'This dataset has no data'

### ISSUE THREAD

**Issue by lukefretwell** [GSA/datagov-wptheme#307]
Seeing "This dataset has no data, why not add some?" message on a number of pages.

Not clear if there's no data or only metadata available or whether it's a data.gov bug or healthdata.gov error.

Example: http://catalog.data.gov/dataset/medicare-provider-charge-data

**Comment by lukefretwell** [comment]
Also, I think it would be nice to have a more accessible/visible link to the GitHub issues page to make it easier for users to submit bugs (I know you love that), but also see that it's a work in progress, you're constantly improving.

**Comment by JeanneHolm** [comment]
In this case, it seems to be a lack of entry for the metadata for the data resource.  Here it seems the solution will be to make the AccessURL field mandatory. @philipashlock do you agree?  That would provide at least the content for something in the data resource area.

**Comment by JeanneHolm** [comment]
This is due to the way that the metadata is being harvested from geospatial sources and a few other entities that do not comply specifically to Project Open Data.  Since, in fact, there is data and resources in each of these datasets, we are removing the confusing language: "Data and Resources: This dataset has no data, why not add some?"  We do validate geospatial sources with FGDC metadata.

This specific dataset is an artifact from an early harvest of the HHS JSON file before we applied full validation.  We are fixing the HHS issues for the next release.

**Comment by kvuppala** [comment]
This is complete now, option that says Add Dataset is now removed.
