### ISSUE TITLE
Pop-ups when leaving DataGov

### ISSUE THREAD

**Issue by MarionRoyal** [GSA/datagov-wptheme#317]
Is there a way to bypass the 6 second pop-ups when going from data.gov to another government site?  Also, can we reduce it to 5 seconds?

**Comment by ErieMeyer** [comment]
Would be great to loop back to OIRA and see about removing it altogether.

@noahkunin @danmunz, how did you untangle that for CFPB?

**Comment by kvuppala** [comment]
In the current plugin we can whitelist some .gov sites to not show the popup, which was implemented for below domains, but the plugin doesnt take wildcard entries like *.gov or *.mil, we plan to enhance this plugin in the future.  

In the meantime we can add more domains to the list as needed to avoid popup, and we will take care of reducing it to 5 seconds in the next release.

performance.gov
usa.gov
usaspending.gov
twitter.com
github.com
gsa.github.io
whitehouse.gov
catalog.data.gov
ars-grin.gov
mrlc.gov
epa.gov
whitehouse.gov
bison.usgs.ornl.gov

**Comment by danmunz** [comment]
Funny you should mention it - we're actually in the midst of re-thinking/re-untangling this policy now. A few points:
- The guidance on this comes from [OMB M-10-23](http://www.whitehouse.gov/sites/default/files/omb/assets/memoranda_2010/m10-23.pdf) _edit: link fixed_, and is pretty clear that a notification to the user is only needed when you're going to a non-government domain. Most agencies have operationalized this to mean ".gov, .mil, or state government websites," but there's no support in guidance for the idea that you need to notify users when headed to another government website. So I'm not sure why you have to have one when directing to another government site.
- The guidance also doesn't _require_ a pop-up; it just suggests that as a way users _might_ be notified. There's pretty compelling circumstantial evidence that these kinds of popups negatively impact user sentiment (see, e.g., [this study](http://www.tandfonline.com/doi/abs/10.1080/00913367.2002.10673678)). More and more government agencies are following the requirement in a different way, by placing an exit link icon next to relevant links, including [Census](http://www.census.gov/privacy/privacy_policy/security_third_party_links.html) and the [City of Baltimore](http://www.baltimorecity.gov/Help/AccessibilityUsability.aspx) (which, admittedly, isn't bound by M-10-23). It's an [industry best practice](http://www.welie.com/patterns/showPattern.php?patternID=outgoing-links) that's also [more accessible](http://www.maxdesign.com.au/articles/external/)!
- The popup that you have on data.gov is admirably short. The flipside of that, though, is that you're _just duplicating the information in the URL bar_. That would make sense, if users didn't pay attention to URLs, but [research shows that people do](ftp://ftp.research.microsoft.com/pub/tr/TR-2007-01.pdf). So if your lawyers are already comfortable with a popup that just shows the URL, maybe they'd buy the argument that you don't need a popup to make sure users see that piece of information.

Anyhow, I hope this is helpful. The whole "popup" thing is one of the odder relics of OMB website guidance, IMHO, but in many cases the myths about what you can/can't/must do are worse than the facts. I'd love feedback on any of these arguments or data points, since as I said, we're in the midst of thinking about this practice within our own agency.

**Comment by danmunz** [comment]
Also, thanks to @ErieMeyer for tapping me into this thread. It's a pretty interesting topic!

![Nerd Alerrrrrt](http://25.media.tumblr.com/tumblr_me36v211YK1rluz0ro1_500.gif)

**Comment by MarionRoyal** [comment]
We don't feel compelled at DataGov to pop-up when going to another government site, but as mentioned we inherited it when we went to WordPress.  I think 6 seconds is an eternity in internet time.

**Comment by danmunz** [comment]
So were you just asking how, mechanically, to disable that feature?

**Comment by MarionRoyal** [comment]
Yes, to find if our techies can only have the pop-ups appear when they are required.  With this refresh of the topic, I'll ping our friends at OIRA to see what their latest advice is.

**Comment by kvuppala** [comment]
we have already reduced it to 5 seconds for the popup instead of 7 seconds, it will go live this Friday.

On the customizing the popup we already don't give popup on some government domain as listed above, we can add more but a longer term solution is to accept the wildcard domain name (eg: *.gov, *.mil) in the wordpress plugin.

**Comment by vz3** [comment]
@kvuppala What is the plugin used for this?

**Comment by danmunz** [comment]
Ah. Well, the relevant file is here: https://github.com/GSA/data.gov/blob/8d912248d34ec9d06047501306c534704c3817a5/themes/roots-nextdatagov/assets/js/ext-link-handler.js

Looks like you can change the delay on the popup by fiddling with line 26.

:::puts away copy of OMB M-10-23:::

:::slinks back into office:::

**Comment by dano-reisys** [comment]
https://github.com/GSA/data.gov/commit/8d912248d34ec9d06047501306c534704c3817a5

**Comment by kvuppala** [comment]
@vz3 we use the Better WordPress External Links
http://wordpress.org/plugins/bwp-external-links/

@danmunz  yes, the code is already updated based on @dan-olaru-reisys comment, will be live this friday on the data.gov site.

**Comment by MarionRoyal** [comment]
I got a response from OIRA.  I am asking if I can quote them.  If not I will paraphrase.  The good news is that there are alternatives to the pop-ups.

**Comment by jedsundwall** [comment]
@kvuppala  In case you want to go ahead and create a massive white list, I've got a list of +7K .gov domains and subdomains. Just let me know.

Also, down with pop ups. They're the worst.

**Comment by kvuppala** [comment]
@jedsundwall the list would be great.

**Comment by ErieMeyer** [comment]
I think there's a dataset of them on data.gov! Not kidding!

**Comment by MarionRoyal** [comment]
@kvuppala 
Lets hold off on this white list
Have a look at
http://www.howto.gov/web-content/manage/categorize/links/linking-policy
I would like for us to consider an alternative notification such as a mouse over disclaimer icons next to the links.  Shall I close this and open a new issue?

**Comment by NoahKunin** [comment]
@danmunz looks like the first link in your comment [the one to OMB] is incorrect. Goes to a Bloomberg article. If you want to edit your hyperlink for posterity, here is the correct URL:

http://www.whitehouse.gov/sites/default/files/omb/assets/memoranda_2010/m10-23.pdf

**Comment by danmunz** [comment]
@NoahKunin Ha, how 'bout that. Thanks.
