### ISSUE TITLE
Change Pop-up external link notification to alternative

### ISSUE THREAD

**Issue by MarionRoyal** [GSA/datagov-wptheme#318]
This follows the close of issue #317 
We need to find an alternative way to notify users when they are going to a non-government site.  The pop-ups we have been using are annoying and not needed according to what I have recently learned.
See http://www.howto.gov/web-content/manage/categorize/links/linking-policy

I have sent an email to the Web Content Manager mail list and I expect to see several examples of how other agencies have accomplished this.

Here is the first response I received from Emma Antunes at NASA

It's not a mouseover, but I implemented a stylesheet to add "(external link)" after non .gov URLs:

---

/\* mark all links that don't include .gov... */

a:link:not([href_=".gov"]):after, a:visited:not([href_=".gov"]):after {
        content: " (external link) ";
        font-size: 90%;
        color: #000000;
}

a:not([href^="http"]):after  {
        display: none;
}

---

and here is an example from Jon Myatt at FWS

Our solution was this alt message for all not ".gov" websites...try mousing over third party links on this site:  http://www.fws.gov/refuge/don_edwards_san_francisco_bay/

Roll over the social media icons...

---

**Comment by danmunz** [comment]
Thanks for following up @MarionRoyal! The alt-text solution seems even more desirable.

**Comment by MarionRoyal** [comment]
Scott Horvath of USGS said:
It would be more user-friendly to simply make the link text/description of the external link be clear enough so people know they're going to a non-gov't site. No scripting, no intercept pages...just good 'ol fashioned plain language. Adding an intercepting page is an extra click, takes time to think, "why am I having to see this every time", etc. 

If you're saying, "Get the full details at the Some NGO Business site" and make "Some NGO Business" the link to the NGO business...well, then you've got descriptive link text and you've set the context for where they're going to be going. 

The CSS icon that Emma mentioned is a good option as well.

If you HAVE to do an intercept page, why not setup the intercept page to only appear the first time someone visits your site and clicks an external link. Let them know that this will only appear once but that it's a notice that you have no control over the content of external sites...then make sure they click a box that says "I agree" (which is just your closing window button/continue button). Then don't have it appear again for that user. Yes...this means using some sort of cookie.

**Comment by MarionRoyal** [comment]
Cheryl Thompson of NIH posted:

Based on general usability principles we:
1. launch sites that are a NEW INTERFACE in a new window.
2. Identify such sites with an icon after the link
3. Added some disclaimer language to the alt text on the icon (to comply with various policies)

Since not every site we link to always supports "back" on the page we target (for example, often scientific paper sites will go through (sometimes multiple) redirects), I, personally, feel that is less confusing to the user to have our base site in a tab than to possibly be lost somewhere else.    With our particular target audience (leans to educated lay public and scientists), I'm not really worried about users being confused that they have gone to a new site, I just want them to be able to get back.

I've seen (it's been years, don't ask for a reference!) usability articles on the use of warning/interstitials where you have to click through a warning for going to new sites, and the results were not very good.

**Comment by MarionRoyal** [comment]
I kind of like the idea of launching non-gov sites in a separate window in addition to an icon.  Do any of you here have an opinion - pro or con?

**Comment by dialsunny** [comment]
HHS.gov seems to have something similar:

![image](https://f.cloud.github.com/assets/5984939/2283821/0ecec642-9fc2-11e3-91e7-e7b1e0765933.png)

**Comment by NoahKunin** [comment]
Sorry for jumping in late!

Now that I've had a chance to re-read [OMB M-10-23](http://www.whitehouse.gov/sites/default/files/omb/assets/memoranda_2010/m10-23.pdf) instead of just scanning it, **I've come to the conclusion that _everyone_ is doing this wrong.** I lump myself into this category, as I should have read this memo more closely three years ago.

The context to this memo was critical. It was written to give agencies clear guidance on potential privacy issues and to a lesser degree, Paperwork Reduction Act implications of using third-party websites _under the control of government agencies_. Especially social media sites. 

From the memo:

> This Memorandum applies to any Federal agency use of third-party websites or applications 
> to engage with the public **for the purpose of implementing the principles of the Open 
> Government Directive.**

Emphasis added. A simple link to a third-party resource is **not governed by this memo** and thus a notification is not needed at all. 

The purpose of the memo is to ensure agencies make users aware of different privacy arrangements on the internet _in those cases_ where the policy of an agency might be confused with that of a third-party site.

> ...government increasingly relies on Federal agency uses of new technologies, such as social media networks and web 2.0 applications. Such uses offer important opportunities for promoting the goals of transparency, public participation, and collaboration. However, increased **use of these technologies also requires greater vigilance by Federal agencies to protect individual privacy.** 

Here's my analysis of the logic of the original memo. Even though almost no one reads the privacy policy of any site, let's imagine for a moment that a citizen **has** read the privacy policy. If that person then clicks a link from AgencyX.gov to a third-party site and sees that third-party site is the Facebook (or Twitter, or YouTube, etc) page of AgencyX, they might rightly presume that the third-party site is governed by the policies of the aforementioned .gov.

Of course this is not the case, as AgencyX has no control over the code base of the third-party site. AgencyX might have signed a modified [TOS](http://www.howto.gov/social-media/terms-of-service-agreements) with the third-party site, but that's an agreement between AgencyX and the third-party itself. It doesn't impact the citizen's use at all. By using the third-party site, our hypothetical citizen is now governed by the site's TOS and privacy policy.

The real meat of this memo appears to be the very first requirement listed:

> a. **Third-Party Privacy Policies.** Before an agency uses any third-party website or application to engage with the public, the agency should examine the third party’s  privacy policy to evaluate the risks and determine whether the website or application  is appropriate for the agency’s use. **In addition, the agency should monitor any changes to the third party’s privacy policy and periodically reassess the risks.**

Regardless of the context of a link being an endorsement or not, government has additional responsibilities to watch out for the privacy of its citizens, especially given recent events.

Notifications that a user is leaving a .gov is only relevant if they understood their privacy rights (or the lack thereof) to begin with. Since this is a rare case indeed, government should instead focus on the first requirement which is to make sure .govs don't send users to sites with abusive privacy and data policies.

As a bit of context, even the White House site has this backwards. The front page of [WhiteHouse.gov](http://www.whitehouse.gov/) does not trigger a notification in any format when users go to social media sites, but does trigger a notification when going to other .govs. Yet, the notification makes no mention of privacy as per the memo's guidance:

> the agency should provide an alert to the visitor, such as a statement adjacent to the link or a “pop-up,” explaining that visitors are being directed to a nongovernment website that may have different privacy policies from those of the agency’s official website

The notification _is_ triggered when going to the personal Twitter pages of WH staff. But this is not the intention of the memo, since a citizen would reasonably conclude a third-party site like this is not under the operational control and therefore policies of the government.

The memo's authors were absolutely well intentioned, but from a social, technological, and design perspective, the memo is fundamentally flawed at this point and is not being implemented in any consistent or rational fashion. Disclosure is important, but disclosure design is important to make it useful. Otherwise it just becomes extra cognitive load without meaning.

Agencies should stop breaking user experience, remove relevant code triggering these notifications or displaying these icons, and should instead re-double efforts to make privacy notices human and machine readable. (more on this last point is forthcoming from me personally)

If OMB could retract or re-write this memo, it would clear up a lot of confusion.

cc @haleyvandyck @eriemeyer @danmunz @philipashlock @gbinal

**Comment by dsmorgan77** [comment]
@NoahKunin it's more than M-10-23. Read M-05-04, agency linking policies. http://www.whitehouse.gov/sites/default/files/omb/memoranda/fy2005/m05-04.pdf

HowTo.gov has implementation guidance: http://www.howto.gov/web-content/manage/categorize/managing-links

**Comment by NoahKunin** [comment]
Thanks for the link! 

I had already read M-05-04. I re-read it again tonight to be certain, and sure enough, there is nothing in that memo compelling agencies to code for any notifications whatsoever re: external links.

What the memo does say under section 6 is entirely reasonable. For example:

> D. OMB’s Information Quality guidelines exclude hyperlinks from the definition of 
> information. This exclusion does not remove agency responsibility to exercise due diligence 
> when determining whether to link externally. Therefore, when an agency determines 
> external links are necessary for and material to the presentation of agency information or the 
> delivery of services in the proper performance of an agency function, they must take 
> reasonable steps to ensure the presentation is accurate, relevant, timely, and complete.

With all due respect to the HowTo.gov team (especially since I work @GSA now!), their guidance is a bit too deterministic given the OMB policy. The HowTo.gov page also doesn't accurately reflect @GSA's own [linking policy](http://www.gsa.gov/portal/content/116617?utm_source=OCM&utm_medium=print-radio&utm_term=HP_11_Footer_linking&utm_campaign=shortcuts), which states that:

> All links and pointers to sites that are not part of the government are identified as "nongovernment links" Such links are either:
> - Collected in a list with the label "Nongovernment Links", or
> - "Described in text as "a commercial site", "a nongovernmental education site", or "a nongovernment public organization site".
> 
> This presentation is GSA’s notification to visitors that these links are to nongovernment sites and that the disclaimers below apply.

While still a little outdated considering modern web norms, it also says nothing of interrupting the user flow with a specific notification or iconography. I'll be reaching out to the various teams here and at OMB to get some updates issued to clarify that matter for web content managers.

cc @polastre @quepol

**Comment by ErieMeyer** [comment]
+1

Perhaps digitalgov.gov can lend a hand, too.

**Comment by gbinal** [comment]
A few thoughts - 
- Agreed that 10-23 isn't at issue here.  
- My understanding is that icons, alt-text, or other much less invasive options than pop-ups are definitely options.  By all means, death to invasive pop-ups.  
- Along with Dan, I've also understood M-05-04 to be the underpinning for this (and an update to it the needed solution), but I agree with Noah that it doesn't spell out this requirement in the document.  
- But in reading around more, I think that the missing element that drove agencies to this was actually the Information Quality Act (a.k.a. Data Quality Act), which is plugged in the memo.  

[More background here](http://www.howto.gov/web-content/manage/categorize/managing-links) and [here](http://www.howto.gov/web-content/requirements-and-best-practices/laws-and-regulations/information-quality), with some ... interesting perspectives on the Act [here](http://en.wikipedia.org/wiki/Data_Quality_Act).  

My guess is that the '[best practices](http://www.howto.gov/web-content/manage/categorize/managing-links)' at issue here came about in response to this rider and the resulting OMB guidance and is the result of the Web Council (or a group of web masters) talking through what they thought made sense for this.  

An email to the web content managers listserve could probably clarify this, but it would seem easier just to not worry about it, use something lightweight like icons and be done with it.  :)

**Comment by NoahKunin** [comment]
Is this actively being worked on by @kvuppala? If so, what is the UX being implemented? Just checked the site and the implementation seems to be all over the place. For example, no interstitial when going to Twitter and GitHub which obviously have different privacy policies, but there is a interstitial when going to GSA.gov which has [should have] the same privacy policy across all of it sites.

Again, I'll advocate for a contextual application using written copy when the delta between privacy policies matter. Interstitials and icons should removed where other design choices make it obvious to the user they are leaving the domain.

**Comment by hkdctol** [comment]
We're leaning that way too. Should be implemented in 2.5

**Comment by NoahKunin** [comment]
Nice, thanks!

**Comment by kvuppala** [comment]
@NoahKunin  We plan to include an icon next to the external links, and also open them in a new window, the extenal icon will include disclaimer language.

**Comment by hkdctol** [comment]
@kvuppala  Probably not. We've been discussing it further while you've been busy on 2.4. We will update soon.

**Comment by kvuppala** [comment]
Got it, missed few of the comments on this thread.

**Comment by philipashlock** [comment]
Here's the current thinking: 
- regardless of this policy, use good link text that makes it clear where the link goes
- for any new links we create where it seems warranted to provide clarification of differing privacy policies, provide a contextual disclaimer on the page using copywriting, design, and layout that's appropriate for the situation. 
- as a last resort, provide simple disclaimer text in the title attribute of the link to be shown as an accessible tooltip (e.g. [providing ARIA attributes with jQuery UI](http://hanshillen.github.io/jqtest/#goto_tooltip)). 
- until this approach is applied for legacy content, provide boilerplate disclaimer text as a tooltip for any non-gov link that doesn't have one we explicitly added
- over time review old links and manually add disclaimer text only where needed
- remove any automated boilerplate disclaimer text after we've reviewed old content or when policy is updated or deprecated

**Comment by dialsunny** [comment]
Old pop-ups have been eliminated and suggested solution has been incorporated for non .gov and .mil sites.
