### ISSUE TITLE
Data.gov CSW what are returnables configured

### ISSUE THREAD

**Issue by mhogeweg** [GSA/datagov-wptheme#355]
It would be helpful for developers of CSW clients to understand what metadata elements are returned from the Data.gov CSW service. Currently it appears that the brief response element set does not include the abstract. This means that even for a simple search page (title, abstract, links) one has to retrieve the full metadata. This puts a strain on the CSW server as well as result in large responses, just for a results page, plus it increases interoperability between CSW clients that interact with multiple CSW services.

an example list of returnables may be found here:
https://github.com/Esri/geoportal-server/wiki/Catalog-Service#Returnables

**Comment by mhogeweg** [comment]
to add to this, it appears for some results, the full response does not include the <code>gmd:fileIdentifier</code> element, while the brief response for the same does.

**Comment by kalxas** [comment]
Thank you @mhogeweg for your comment.
The CSW elements are mentioned in the data.gov documentation, but this Table 6 you are including in your documents is really helpful. I will see if we can integrate to our documentation too.
The rest is "by the book" as usual ;)

**Comment by kalxas** [comment]
@mhogeweg regarding your second comment, can you please share an example of the issue? Thanks.

**Comment by mhogeweg** [comment]
here you go. we host a [simple CSW client](http://gptogc.esri.com/postXML/) where you can post the below XML as part of our [Geoportal Server sandbox](http://gptogc.esri.com). I use http://catalog.data.gov/csw-all as the CSW endpoint.

Below request does not include <code>gmd:fileIdentifier</code> value, while using csw:ElementSetName = brief does include it. This value is key as it is used to then later issue the <code>GetRecordById</code> request to retrieve a full view of the metadata.

```
<?xml version="1.0" encoding="UTF-8"?>
<csw:GetRecords xmlns:csw="http://www.opengis.net/cat/csw/2.0.2" version="2.0.2" service="CSW" outputSchema="http://www.isotc211.org/2005/gmd" resultType="results" startPosition="1" maxRecords="10">
  <csw:Query typeNames="gmd:MD_Metadata" 
    xmlns:dc="http://purl.org/dc/elements/1.1/" 
    xmlns:gmd="http://www.isotc211.org/2005/gmd" 
    xmlns:ogc="http://www.opengis.net/ogc" 
    xmlns:gml="http://www.opengis.net/gml">
    <csw:ElementSetName>full</csw:ElementSetName>
    <csw:Constraint version="1.1.0">
      <ogc:Filter xmlns="http://www.opengis.net/ogc">
        <ogc:PropertyIsLike escapeChar="!" singleChar="#" wildCard="*">
          <ogc:PropertyName>apiso:AnyText</ogc:PropertyName>
          <ogc:Literal>mannington</ogc:Literal>
        </ogc:PropertyIsLike>
      </ogc:Filter>
    </csw:Constraint>
  </csw:Query>
</csw:GetRecords>
```

**Comment by kalxas** [comment]
Thanks @mhogeweg I was able to reproduce this.
With the above POST request we are getting an empty gmd:fileIdentifier
If we change csw:ElementSetName=full to csw:ElementSetName=brief then we get a non empty gmd:fileIdentifier

This comes down to the way things are set up:
CKAN is harvesting from various sources and transforms everything to ISO XML.
This basically means that some records do not have fileIdentifier.
Then in CKAN, a harvested_source_identifier is created and stored in the database (but not inserted to the ISO XML as fileIdentifier).

Then pycsw gets the ISO XML, parses and stores it in the CSW database.
Since pycsw will not accept an ISO without an identifier, this is what happens:
https://github.com/kalxas/ckanext-spatial/blob/51-arcgis-pycsw/bin/ckan_pycsw.py#L248

If no fileIdentifier in the XML, the ckan harvest identifier is used as the record identifier and stored in the pycsw database in the fileIdentifier field (similarly to CKAN, pycsw does not hijack the original XML by inserting the identifier into the original record)

So the result is the following:
For ElementSetName=full and outputSchema="http://www.isotc211.org/2005/gmd" pycsw ALWAYS returns the original XML as harvested by CKAN (which in this case misses the fileIdentifier).
For ElementSetName brief or summary, pycsw creates a response from the database fields, thus you get the ckan identifier in your response.

We are working on this issue.

**Comment by kalxas** [comment]
In order to fix, we need either CKAN or pycsw to insert the harvested_source_identifier in the ISO XML (IF fileIdentifier is empty)

**Comment by kvuppala** [comment]
This is complete now.
