### ISSUE TITLE
Impact Section Improvements

### ISSUE THREAD

**Issue by JeanneHolm** [GSA/datagov-wptheme#361]
Several people have made suggestions on how to improve the Impact section on Data.gov.  These include:
  --Adding a topic for Accountability and Transparency, including examples of impacts (Alex Howard https://twitter.com/digiphile/status/453600711780356096)
  --Looking at the idea of social, political, and economic impacts (@philipashlock https://twitter.com/philipashlock/status/453603543598264320)
  --Expanding to include the rest of the topics on Data.gov and others (in addition to the above) (John Wonderlich https://twitter.com/JohnWonderlich/status/453613695193858049)
  --Providing concrete examples (Alex Howard https://twitter.com/digiphile/status/453612227023888385)
  --Additional non-commercial examples (Greg Brown https://twitter.com/GregBrownm/status/454308363174961153)

**Comment by rebeccawilliams** [comment]
While we've seen a number of great presentations on how open data can spur economic activity, it'd be great to see data.gov take the lead on showing impact examples of where open data creates transparency, empowers accountability, enhances efficiency (and leads to cost savings), improves service quality (including making it more equitable), increases public safety, and increases civic engagement. It'd be great to see this lens inform not just the channels, but also the values highlighted currently in the right sidebar (as of this issue those only include: location, financing, jobs). 

The Sunlight Foundation local team recently gathered a few [Impacts of Open Data](http://assets.sunlightfoundation.com.s3.amazonaws.com/documents/policy/impacts-of-open-data.pdf) that include many of these additional impacts. This is just a small sample of impact examples out there that we hope to grow with help from data.gov and other folks in the open data community.

**Comment by JeanneHolm** [comment]
Great idea @rebeccawilliams @digiphile and @johnwonderlich.  Appreciate your work in gathering these excellent examples and look to integrate many of them on Data.gov.  This issue is currently on track for inclusion in our release in May (in time for the National Civic Day of Hacking): https://github.com/GSA/data.gov/issues?milestone=15&state=open

**Comment by GovInTrenches** [comment]
Pinging on this from @SmartChicago side - we have a similar resource with our blog at [http://www.smartchicagocollaborative.org] and would be happy to crosspost. I can start converting our post into the appropriate format once we know for sure what that is (Wordpress, .md, ect)

**Comment by rebeccawilliams** [comment]
Two additions to more examples, that should be included in these improvements: 
- [x] An updated intro to include other types of impacts (listed above)
- [x] A link to way users can submit examples; the first iteration might simply be a link to the contact page.

**Comment by philipashlock** [comment]
@rebeccawilliams FYI - http://sunlightfoundation.com/blog/2015/01/23/help-us-build-an-evidence-base-on-the-social-impact-of-open-data/

**Comment by rebeccawilliams** [comment]
@philipashlock yup, I flagged that activity in #464 too. There are only a few U.S. examples collected there so far, and many are using scraped or crowdsourced data, but I am looking forward to more examples and keeping an eye on it.  

It would be interesting to explore better ways to collect this information on Data.gov though. A few ideas: 

**Multiple Crowdsourcing Routes** 

For example, France, in addition to having [a section on their open data site dedicated to Dataset "Reuse"](https://www.data.gouv.fr/fr/datasets/plf-2014-budget-general-bg-par-destination-mission-programme-action-titre/), has a "+ a Reuse" button on each dataset page, see [this dataset](https://www.data.gouv.fr/fr/datasets/plf-2014-budget-general-bg-par-destination-mission-programme-action-titre/)'s reuses here: 

![screen shot 2015-02-23 at 9 36 48 pm](https://cloud.githubusercontent.com/assets/1725454/6342318/1fa98740-bba5-11e4-86d9-957420021b67.png)

I really like this approach because it connects the data and its reuse more directly and it also gives the public a way to engage directly on the dataset page. Keeping in mind the Project Open Data requirements and the Data.gov harvest process: 
1. Is it possible to provide something like this at the dataset level that is sustainable?
2. Could other policy requirements like reporting [Use and Impact](http://labs.data.gov/dashboard/offices) be directed to a structured form that also propagates Data.gov? cc @jlberryhill. 

**Partnering** 
How could Data.gov better facilitate or connect these impact (and app) roundups with partners like, but not limited to: Code for America, ODI, OKF, Gov Lab, Pew ([see their All Things Census project](https://twitter.com/allthingscensus)), SmartChicago (above), Socrata, Sunlight Foundation, etc.

**Automation**
How can we better automate Impact (and Application) discoveries?
- #464 
- APIs (like the CFAPI)?
- ?

**Comment by rebeccawilliams** [comment]
Impacts have been expanded: https://www.data.gov/impact/

A larger redesign would be something to consider in the future (as another issue) to better support more examples.
