### ISSUE TITLE
"Highlights" section for each of the Community pages

### ISSUE THREAD

**Issue by rypan** [GSA/datagov-wptheme#37]
Feature request from @nsinai

Each community should have the ability to feature X number of datasets on their community page. This functionality should feel like http://highlights.data.gov.

**Comment by rypan** [comment]
We need to figure out how to build this one out. Is it just making certain post types as sticky? Do we create a plug-in that stores a different set of data to the database?

**Comment by JeanneHolm** [comment]
The functionality has been built so that from a community page someone can view a community-curated list of related datasets.  For example, Research community --> Data --> Curated datasets
Research community:  http://next.data.gov/research/
Click on Data tab at top yields: http://catalog.data.gov/dataset?_groups_limit=0&groups=research9385
Note this doesn't look like highlights.data.gov, but provides a stronger way for curation within the active catalog and will allow agencies to also tag datasets for possible inclusion in community curated models.
