### ISSUE TITLE
Organizations: Suppress those with zero datasets

### ISSUE THREAD

**Issue by dsmorgan77** [GSA/datagov-wptheme#401]
Now that DOT data.json is being harvested, all datasets are listed under the single organization (http://catalog.data.gov/organization?q=transportation&sort=name+asc). Bureaus that were previously listed as organizations now have zero datasets. They shouldn't be listed.

**Comment by philipashlock** [comment]
This should now be complete for DOT, VA, and GSA and we'll be reviewing others and making sure this is incorporated into the process for any future initial migrations to the data.json harvesting for an agency. This is a little more complicated than you'd expect because we're still trying to preserve some information about legacy datasets that were included in each of those organizations.

**Comment by rebeccawilliams** [comment]
@philipashlock, Flagging this Issue because it looks like this problem was resolved, but happy to leave it open if there are any next steps to take here.
