### ISSUE TITLE
Deleted Harvest Sources are still checked against for URL matching, preventing creation of "new" harvest sources utilizing that same url for harvestable resources

### ISSUE THREAD

**Issue by wheelebk** [GSA/datagov-wptheme#406]
I set up a private test harvest from our Web Accessible Folder to ensure that our updated records would work before replacing/writing over current versions in catalog.data.gov.  I then deleted the test harvest source, and attempted to move our current harvest source for USGS Core Science Analytics and Synthesis to the same WAF used in the test harvest.  I receive an error that another harvest source is already using that WAF, even though I've deleted it.

**Comment by kvuppala** [comment]
@wheelebk when the harvest source is deleted, they are soft deleted first, and by the next day they are hard deleted so that same harvest source URL or harvest soruce name can be utilized.  

The soft delete was only  a measure to recover from a user mistake which gives additional day to recover, if you try to recreate the harvest source now it should work fine.

**Comment by rebeccawilliams** [comment]
@wheelebk has this Issue been resolved?

**Comment by wheelebk** [comment]
Hi,

It did work great!  Thanks again for the assistance!

Ben

Ben Wheeler
Core Science Analytics, Synthesis, and Libraries (CSAS&L)
Core Science Systems (CSS)
United States Geological Survey (USGS)
Room 9213, Bldg 810, MS 302, Denver Federal Center
Denver, CO 80225
303-202-4663
bwheeler@usgs.gov

**Comment by rebeccawilliams** [comment]
Excellent!
