### ISSUE TITLE
Proposed AAPI topic area

### ISSUE THREAD

**Issue by ErieMeyer** [GSA/datagov-wptheme#424]
Hi all -- Kicking off this issue so we can gather the artifacts around the proposed AAPI topic area.

**Comment by JeanneHolm** [comment]
The plan for this is to include a catalog view, rather than a front page topic.  This means that users will be able to see datasets from catalog.data.gov, but will not have additional context or content related to the Asian American and Pacific Islanders (AAPI) topic.  That content will be at another site to be determined by the AAPI team.  An example of this is shown for "Biology and Habitats" http://catalog.data.gov/dataset?vocab_category_all=Biology+and+Habitats&_vocab_category_all_limit=0

**Comment by JeanneHolm** [comment]
There will be a view of the catalog for datasets related to this topic, but the content will reside at http://www.whitehouse.gov/administration/eop/aapi/data/facts-and-figures.
