### ISSUE TITLE
Ability to roll API Key

### ISSUE THREAD

**Issue by benbalter** [GSA/datagov-wptheme#427]
I signed up for an API key for `api.data.gov` which was an absolutely :sparkles: experience.

I then went ahead and committed that to a repository, as one does. (whoops!)

I created a new key, but it'd be great if there was some way to invalidate and roll the old key.

:lock:

**Comment by GUI** [comment]
Good idea. We don't have anything like that yet, but we'll certainly keep it in mind (I think it fits in nicely with some broader api key plans we have).

In the meantime, I'd be happy to invalidate the key manually for you. Can you share the Account ID of the api key in question? The Account ID should be the UUID in small text on the confirmation screen or the e-mail you got. If you don't have that handy, then I guess sharing the api key should be fine, since I'll be disabling it. Or we can bring this to e-mail if you'd prefer.

**Comment by philipashlock** [comment]
@GUI Should we migrate issues like this to https://github.com/NREL/api-umbrella?

**Comment by rebeccawilliams** [comment]
@GUI pinging this and [other Data.gov Issues labeled API](https://github.com/GSA/data.gov/labels/APIs) for your consideration. :heart:

**Comment by GUI** [comment]
Oops, so sorry for the super-long delay! I moved this issue over to the api.data.gov repo where we're trying to consolidate any feature requests or issues: https://github.com/18F/api.data.gov/issues/132

I'm not sure we have immediate plans to implement this, since our API keys are pretty freely available for accessing public data, but it is something I'd like to get to someday. However, if anyone ever wants a key invalidated in the meantime, just get in touch, and we can do that manually.

Feel free to close this if you're happy migrating it over to that api.data.gov issue we can track over there.

**Comment by rebeccawilliams** [comment]
It makes sense to me to better track this particular issue at [18F/api.data.gov](https://github.com/18F/api.data.gov), so I am closing it here. Thanks @GUI!
