### ISSUE TITLE
De-duplicate records

### ISSUE THREAD

**Issue by philipashlock** [GSA/datagov-wptheme#448]
An example for SSA:
http://catalog.data.gov/dataset/social-security-administration-ssa-new-court-cases
http://catalog.data.gov/dataset/social-security-administration-ssa-new-court-cases-67d4c

An example from GSA:
http://catalog.data.gov/dataset/data-gov-visitor-metrics
http://catalog.data.gov/dataset/data-gov-visitor-metrics-bdcca

**Comment by FuhuXia** [comment]
CKAN datajson harvester will update the dataset if: 1). same harvester source 2). same identifier. Otherwise it will insert as new dataset.

For the given examples, SSA first record's has no identifier. Obviously the extras__identifier got lost by some kind of mistake. Therefore the 2nd insert.

For the GSA example, the first record has no harvester source associated. It is either created by manual input, or the harvest source got lost.

In either case, we can look at the dataset history and find out the root cause, and scripts can be developed to target for different root cause and clean up the bad datasets via ckan api.

**Comment by philipashlock** [comment]
The duplicate from separate harvesters makes sense. I think the issue with the identifier might be a legacy from an old version of the harvester (that SSA record is from March). If that issue is no longer present, then we should just focus on doing a scan of any duplicates that were generated and work to de-duplicate them

**Comment by FuhuXia** [comment]
I tried to develop some queries to filter out all datasets that fit in the two scenario above mentioned in the two examples. It turns out these two examples are pretty unique. No other datasets can be found that have same issues.

First query shows the SSA example is the only duplicate we can find
http://catalog.data.gov/api/search/dataset?q=extras_rollup:*

Second query shows the GSA example is also the only duplicated dataset. There are two other datasets in the query result, but they got no duplicated dataset, therefore I don't want to delete them yet.
http://catalog.data.gov/api/search/dataset?q=identifier:*+AND+-harvest_source_id:*

I will manually delete these two duplicated datasets in the examples. no script needed.
1. /dataset/social-security-administration-ssa-new-court-cases
2. /dataset/dataset/data-gov-visitor-metrics

**Comment by rebeccawilliams** [comment]
I found another example (with an older February record), which suggests this might be a larger problem:
- https://catalog.data.gov/dataset/fda-pet-food-recalls
- https://catalog.data.gov/dataset/fda-pet-food-recalls-cea69

**Comment by FuhuXia** [comment]
This is due to legacy HHS data. HHS data got into our system before datajson extension is mature yet. Will address them in customized script.

**Comment by FuhuXia** [comment]
@kvuppala 
http://catalog.data.gov/dataset/social-security-administration-ssa-new-court-cases
has been deleted, and should be redirected to 
http://catalog.data.gov/dataset/social-security-administration-ssa-new-court-cases-67d4c

http://catalog.data.gov/dataset/data-gov-visitor-metrics
has been deleted, and should be redirected to
http://catalog.data.gov/dataset/data-gov-visitor-metrics-bdcca

**Comment by kvuppala** [comment]
I have actually renamed as below to keep the better URLs

http://catalog.data.gov/dataset/social-security-administration-ssa-new-court-cases-67d4c to http://catalog.data.gov/dataset/social-security-administration-ssa-new-court-cases

http://catalog.data.gov/dataset/data-gov-visitor-metrics-bdcca to http://catalog.data.gov/dataset/data-gov-visitor-metrics

Will be adding the redirects from the first URL to second URL

**Comment by rebeccawilliams** [comment]
Flagging #476 here as well.

**Comment by philipashlock** [comment]
@FuhuXia Looks like there are still a dozen or two HHS datasets with duplicate IDs:
http://catalog.data.gov/api/3/action/package_search?q=organization:hhs-gov&facet.field=identifier&facet.limit=-1&facet.mincount=2

**Comment by kvuppala** [comment]
@FuhuXia @philipashlock 
Checked few examples of duplicate identifier, the duplicates have come from a different harvest source associated to hhs-gov organization (http://catalog.data.gov/harvest/hhs-cas-json)   

http://catalog.data.gov/dataset?q=%223feb5024-2ba1-4110-9c73-fee5c0f82e26%22&sort=score+desc%2C+name+asc
http://catalog.data.gov/dataset?q="fa10d4bc-34fc-4a7f-b67d-fa3665e2eb28"&sort=score+desc%2C+name+asc

The second harvest source (http://catalog.data.gov/harvest/hhs-cas-json ) for hhs-gov has 16 datasets, looks like all these 16 seems to have duplicates in main HHS harvest source  (http://catalog.data.gov/harvest/healthdata-gov)

I guess we can confirm and remove this harvest source from catalog.

**Comment by kvuppala** [comment]
once confirmed from hhs-ckan-json harvest source, we can delete the data to remove the duplicates.

**Comment by philipashlock** [comment]
@kvuppala Let's prepare redirects for the 16 datasets from harvest/hhs-cas-json  before we delete them.  It looks like most of these have the preferred URL without the extra hash string, so if if we can retain those URLs, associate them with the current harvest source, and redirect to them, that'd be best.

**Comment by kvuppala** [comment]
@philipashlock 
Sure, looks like some of the hhs-cas-json records have extra hash, will retain the good URLs without hash between the two harvest sources, and redirect the other ones appropriately.

**Comment by kvuppala** [comment]
@philipashlock 
Looks  like this one particular dataset doesnt have  a replacement from healthdata.gov json source.
http://catalog.data.gov/dataset/service-locator-comprehensive-healthcare

Also noticed that hss-cas json source  is at https://raw.githubusercontent.com/gbinal/data/master/datasets/hhs_cas.json,  assuming Gray created test source.   

Rest we will get the redirects placed, and then delete this harvest source.

**Comment by kvuppala** [comment]
duplicates from hhs cas json have been deleted, all the good URLs are retained and  the necessary redirects are  put  in place.
