### ISSUE TITLE
Provide broken link report for catalog

### ISSUE THREAD

**Issue by philipashlock** [GSA/datagov-wptheme#459]
This was discussed in https://github.com/GSA/data.gov/issues/171#issuecomment-44301663 using the archiver extension and that has been installed but I wanted to make sure this particular feature had it's own issue to make sure it was fully implemented.

**Comment by kvuppala** [comment]
We should plan this for 2.11. 

The current report extension does not work out of box with our ckan core. It was built for ckan core after 2.1. We are on 2.0, or 2.1a to be exact. 

We can either upgrade our ckan core to 2.1 or later, or re-code part of the report extension to make it work with our ckan. The first one involves a lot of work. The latter is easier.

**Comment by ydave-reisys** [comment]
As part of 2.11 release we will be implementing only 1st page of broken-link report. Ckanext-report extension requires ckan 2.2. Hence we are modifying extension to work with ckan 2.1 version. Extension gives only framework and have to do coding to get custom reports.

**Comment by rebeccawilliams** [comment]
Adding we should make this conspicuous (and/or blog about) the broken link report, see this as an example: http://data.gov.uk/blog/fixing-broken-data-links

**Comment by kvuppala** [comment]
Broken link report is added part of the release, the cron is running in staging instance to check all the links, once finished we will plan to run this in live site in the next few days.

**Comment by kvuppala** [comment]
Broken link report cron is improved to run in parallel (about 10 threads) to accommodate the huge amount of data we have in the catalog, however things are still a bit slow as some of the external agency links are not accessible in live environment due to some firewall / networking issues,  in the  last two weeks only 200K datasets were processed and still another 1 million to go through, if we run into any huge agency list which has above issues it could slow down even further.

We plan to setup a proxy server outside of production environment probably in amazon or so to go through these resource links to identify broken links,  and also dynamically collect the  bad domains which are completely down or have some network issues so each dataset is not processed fully for those domains,  each full broken link report cron will start with zero domain and as the process  finds they will added to fasten the report generation.    Plan to complete this enhancement in 2.16 release.

We will continue to monitor the current cron for next few days, and if not complete we will stop it for the crucial release planned in Apr first week to avoid resource constraints  on the production system.

**Comment by kvuppala** [comment]
@philipashlock @FuhuXia 
Looks like we may not need a proxy solution in amazon for now,  we learnt that few URLs that were not working in production / internal environment are due to the fact that these IPs were blocked from accessing the links, we are going to coordinate in opening up these restriction as we have a business need to access these URls.

**Comment by kvuppala** [comment]
Made few updates to this broken link report:
- HEAD requests have been introduced to be made prior to GET requests, which must optimize cron script.  But it will not be enabled in production as we noticed few agencies have blocked data.gov access to restrict many requests to their site. 

Below updates are pending to optimize the entire report execution:
- mark same domain urls unreachable if domain did not work for several urls in a row 
- validate url using firs N bytes, instead getting the whole document. So when we are able to get N first bytes of the document, then the document exists.
- get resource URLs randomly from the Queue, so we don't do same agency website url requests in a row

**Comment by kvuppala** [comment]
Below updates are complete and the QA cron is running in production:
- validate url using firs N bytes, instead getting the whole document. So when we are able to get N first bytes of the document, then the document exists.
- get resource URLs randomly from the Queue, so we don't do same agency website url requests in a row

One change pending is below:
- mark same domain urls unreachable if domain did not work for several urls in a row 

Will move it to 2.18 to finish the rest of the task.

**Comment by kvuppala** [comment]
Updates :

2 weeks ago the full broken link report cron finished on the production, and since then the daily cron has been running.  However we have noticed that daily cron doesn't finish as per our estimate as there is more data to catchup since the full cron start date and there is a need to put the daily cron on the supervisor control to ensure only one daily incremental cron is running. 

Link http://catalog.data.gov/report/broken-links can be seen for the initial report on the number of broken links, datasets with broken links.  

Also the code enhancement is complete to address the unreachable domains, which take up lot of time during the broken link report checks.

New Pending List on this:
- Add the daily cron to supervisor control to ensure only one job run at a time
- Some of the agency pages which has huge data doesnt load correctly, we need to find ways to cache these pages locally after the cron is complete.
- Also FTP links are listed as broken which are working @ http://catalog.data.gov/report/broken-links/azgs-az-gov , we need to look at if there is any code issue or the links were broken when the report did get generated.

Pending ones will be addressed in 2.19

**Comment by kvuppala** [comment]
Pending tasks listed above are completed, once code change pending which is tracked at https://github.com/GSA/data.gov/issues/656 

Closing this task.
