### ISSUE TITLE
Merge Cities, Counties, and States into new Local topic

### ISSUE THREAD

**Issue by philipashlock** [GSA/datagov-wptheme#474]
This should mostly be content management updates, but there are a few code changes needed for the template: 

Code changes
- [X] CSS changes - use the states icon for the new Local topic
- [X] Update the frontpage template to remove the defunct topics and add the new one

CMS updates:
- [X] Create new topic
- [x]  Assign all pages and posts from old topics to the new one
- [ ] Create redirects from old pages and topic landing pages to this new one

**Comment by rebeccawilliams** [comment]
I renamed this to be broader. In addition to merging the Topic information, the data should be merged.

**Comment by kvuppala** [comment]
@rebeccawilliams @philipashlock 
All the three Cities/Counties/States topic datasets are now tagged to Local Govt topic/group that is created in catalog http://catalog.data.gov/group/local, also added a new menu option on the https://www.data.gov/local/ topic Data tab for "All Local Government"  data, linking to https://catalog.data.gov/dataset?groups=local#topic=local_navigation to display all datasets.

Updated all the Cities/Local/States/County harvest sources to automatically tag to this new group/topic "Local Government", anything we add in the future should be defaulted to this group.

ToDo:
Since we wanted to keep the Cities/States/Counties sub menu options in the Data tab, we will need to minor changes on the catalog to show the Local Govt topic menu all the time, and minor CSS changes within the data tab,  if were were to removed three sub menu and just have the Data link to the URL https://catalog.data.gov/dataset?groups=local#topic=local_navigation it would have worked well without above changes, and the users will still be able to filer datasets by the facet "Organization Types" similar to the direct sub menu links.

**Comment by rebeccawilliams** [comment]
@kvuppala what's the status of these last To Dos?

**Comment by kvuppala** [comment]
@rebeccawilliams 
sorry forgot to reply on this, the changes are complete as of this tuesday.  I think this can be closed.

**Comment by rebeccawilliams** [comment]
Thanks! Closing this.
