### ISSUE TITLE
Trying to request catalog.data.gov/data.json results in error

### ISSUE THREAD

**Issue by dmfenton** [GSA/datagov-wptheme#475]
Not surprising since its such a huge file but I need to access this data. Maybe implement pagination? Anyhow, how can I get a set of results just for the census bureau with metadata and links to all the distributions?

![image](https://cloud.githubusercontent.com/assets/7832202/4483182/0b885be6-49af-11e4-8fd4-a9c1657955d9.png)

**Comment by rebeccawilliams** [comment]
Hi @dmfenton,

Flagging the [tweet](https://twitter.com/dmfenton/status/517679037745885186) and highlighting relevant Issues:
- #180 
- #294 
- & to a lesser extent #315 

Is there any other [Data.gov CKAN API documentation](https://www.data.gov/developers/apis) (other than queries filtered by organization) that might be helpful here?

**Comment by philipashlock** [comment]
@dmfenton You can filter for Census using the CKAN API, eg http://catalog.data.gov/api/3/action/package_search?q=organization:census-gov and then paginate through the results with the `rows` and `start` parameters as described in the CKAN API documentation. Unfortunately some of that metadata may not be as current as it could be since the Department of Commerce (which Census is a part of) is one of the few agencies that's still in the midst of the transitioning to making their data available using data.json and a single department-wide source of metadata. 

In case it's helpful, most of the Census metadata is pulled directly from these sources: http://catalog.data.gov/harvest?organization=census-gov&_organization_limit=0

We're also working to make the entire corpus of metadata on data.gov more easily available as a bulk download rather than just the API. Since that is already being tracked with #315, I'll go ahead and close this one, but feel free to comment again if you need more help with what's available now.
