### ISSUE TITLE
Duplicate records getting reharvested back into data.gov from state sites

### ISSUE THREAD

**Issue by amilan17** [GSA/datagov-wptheme#476]
Metadata records federated from state.data.gov sites are republished back to data.gov (via JSON) resulting in duplicate metadata records in data.gov. 
For example, a search for "Marine+and+Lacustrine+Geological+Samples" in data.gov results in the 
duplicate entries.
https://catalog.data.gov/dataset?q=%22Marine+and+Lacustrine+Geological+Samples%22&sort=score+desc%2C+name+asc

From what I can tell, it looks like one record (https://catalog.data.gov/dataset/index-to-marine-and-lacustrine-geological-samples-imlgs) is getting republished by data.hawaii.gov, data.illinois.gov, data.ok.gov and data.oregon.gov.

When I go to the state sites and perform the same search above - I only get results from the federated data.gov site.

I hope this is the best place to register this issue - if not, please let me know.

**Comment by rebeccawilliams** [comment]
Thank you @amilan17! This is perfect place for this feedback. We've flagged this as a priority and are looking into this.

**Comment by philipashlock** [comment]
Socrata is working on updating their data.json generation to filter out federated sources. In the meantime, we'll pause new harvests and use the following approach to remove the duplicates on our side. Unfortunately, there are currently no distinguishing characteristics in the Socrata data.json metadata to know whether it was federated from data.gov or not, but we can filter for the source using the Socrata API. 

This issue only seems to be coming from four sources: 
- Hawaii  
- Oregon  
- Oklahoma
- Illinois

but since they all have the same copies, we can just query one of them to get all the Unique IDs we need that are duplicated (4 times) on catalog.data.gov. Here's the relevant query for Oregon's endpoint where we specify the federation source we want (in this case 19 is the id for explore.data.gov):

`https://data.oregon.gov/api/search/views.json?federation_filter=19&limit=50&page=1`

We can paginate with the limit and page parameters to get through all records. On each record we get the view id and use that to delete all matching records from these sources on catalog.data.gov. The first view id in the above API call is `vcqj-eg24` 

We can then filter for that id on the relevant organizations on catalog.data.gov with the following API call: 

`http://catalog.data.gov/api/3/action/package_search?q=identifier:vcqj-eg24%20AND%20organization:%28state-of-oregon%20OR%20state-of-illinois%20OR%20state-of-oklahoma%20OR%20state-of-hawaii%29`

**Comment by kvuppala** [comment]
Duplicates are removed, and the harvest sources are put on a daily reharvest schedule.
