### ISSUE TITLE
Missing Twitter Logo Image

### ISSUE THREAD

**Issue by dialsunny** [GSA/datagov-wptheme#511]
![image](https://cloud.githubusercontent.com/assets/5984939/5004293/865dd400-69e8-11e4-9e9a-9d681bea6766.png)

**Comment by philipashlock** [comment]
It seems like there we're relying on a cache and I don't know that there really are any persistent URLs for these. For now it probably makes sense to remove the images altogether. I think it's also worth re-evaluating the syndication and republishing of tweets to be more dynamic and limited to recent tweets, or more targeted and ad-hoc for specific ones that should be featured, or a little bit of both

**Comment by kvuppala** [comment]
@philipashlock looks like when the tweets get old and images are  not cache, we are seeing the issue. 

So far we have four twitter accounts we pull automatically, usdatagov tweets are automatically published, all other three (HealthDataGov, SafetyDataGov, energydatagov) requites manual posting from twitter plugin we use.

We could either host these twitter handle images locally or remove them completely, if we remove should we just use the regular twitter logo that we use in the footer?

**Comment by kvuppala** [comment]
can be closed, main twitter logo is used instead of the individual twitter account handle.  see the attached screenshots.
![twitter_screenshot_developer_page](https://cloud.githubusercontent.com/assets/1738764/5304022/c0292d0c-7bbc-11e4-8ec2-4d60924df7d7.png)
![twitter_screenshot_home_page](https://cloud.githubusercontent.com/assets/1738764/5304021/c0279e92-7bbc-11e4-97ad-3d81f5d1df3f.png)
