### ISSUE TITLE
Various harvest issues

### ISSUE THREAD

**Issue by rebeccawilliams** [GSA/datagov-wptheme#521]
Here are some things I have noticed: 
- [ ] **Catalog links changing often** e.g. http://catalog.data.gov/dataset/missouri-congressional-districts -> http://catalog.data.gov/dataset/missouri-congressional-districts-05a14
- [ ] **Non- "Landing Page" URLs being broken. For the URL example above**

![screen shot 2015-04-02 at 2 44 28 pm](https://cloud.githubusercontent.com/assets/1725454/6970917/bfd9cea0-d946-11e4-91c1-44f3f9f23863.png)
- [ ] **Not harvesting "Maps" from Socrata sites?** e.g. This dataset from Chicago used to be on Data.gov: https://data.cityofchicago.org/Community-Economic-Development/Boundaries-Zoning-Districts/ys52-bf79 but is no longer: https://catalog.data.gov/dataset/boundaries-zoning-districts-b2e4c

**Comment by rebeccawilliams** [comment]
See also, every link but the landing page for Chicago: https://catalog.data.gov/dataset/boundaries-zoning-districts-b2e4c

**Comment by rebeccawilliams** [comment]
@takahiko-naito, @kvuppala do you have insights as to why these issues are happening and next steps?

**Comment by kvuppala** [comment]
@rebeccawilliams, @takahiko-naito 
if a dataset is created in the initial harvest, and in the subsequent one if the identifier is not changed then the URLs should remain as is.

I have noticed in one of the state harvest source, where the identifier got changed in the second run which causes the first record with old identifier to delete and second record with new identifer be created for the first time,  since the deletions are soft deletes for a day CKAN generates a new URL to be unique.

**Comment by kvuppala** [comment]
@rebeccawilliams Also i am renaming the URL of the dataset to remove the unqiue code at the end, will have the redirect setup soon for it. 

Changing URL from  http://catalog.data.gov/dataset/missouri-congressional-districts-05a14 to http://catalog.data.gov/dataset/missouri-congressional-districts

**Comment by philipashlock** [comment]
@rebeccawilliams none of these issues are really about Socrata, so I've renamed the issue again. 

The issues with http://catalog.data.gov/dataset/missouri-congressional-districts seem to be caused by the underlying source data not being available (at an [ArcGIS endpoint](https://ogi.oa.mo.gov/ArcGIS/services/legisDistrict/MapServer)), rather than an issue with Socrata. You can see the same problem on the source page - https://data.mo.gov/Government/Missouri-Congressional-Districts/gz5d-nydj 

Unfortunately there's no contact information provided with this dataset and the contact form for the dataset on the Socrata page doesn't work (perhaps because no email was provided). I also didn't see any contact information for data.mo.gov at all, but I reported this through the main contact form on mo.gov. Maybe @ajturner has an idea of how to track down the maintainer of that broken ArcGIS server. 

The issue with the Chicago datasets appears to be one of [validation](http://labs.data.gov/dashboard/validate?schema=non-federal-v1.1&output=browser&datajson_url=http%3A%2F%2Fdata.cityofchicago.org%2Fdata.json&qa=true). Some of these are an issue with an invalid email provided. We don't require an email for non-federal sources, but if they provide something, it needs to be correct. I'm also seeing some validation issues caused by a `mediaType` syntax that falls outside of our specification, where the charset is included. I've noted this on project open data https://github.com/project-open-data/project-open-data.github.io/issues/464 but for now we'll need to follow-up with data.cityofchicago.org to fix these issues.

**Comment by astauffer** [comment]
@philipashlock It looks like the arcgis URL referenced from http://catalog.data.gov/dataset/missouri-congressional-districts is not correct. When I click to download the CSV, I get this error:

{
  "error" : true,
  "message" : "There is a problem connecting to ESRI service at https://ogi.oa.mo.gov/ArcGIS/services/legisDistrict/MapServer: The server sent HTTP status code 400: Bad Request"
}

The URL might be missing 'rest', but i'm not sure if your call to download is using SOAP. If that's the case then you do not need REST.  The bigger issue appears to be that the services may have also moved into a folder now called LEGIS. There are also several layers available from the Map Server and the Congressional Districts are 2.

The live REST URL is here:
https://ogi.oa.mo.gov/arcgis/rest/services/LEGIS/legisDistrict/MapServer/2

Ping me if you have any more questions, if we need to contact the Administrator of the server I can do so.

cc @ajturner @rebeccawilliams

**Comment by JJediny** [comment]
Added specific broken link report to Data.gov Helpdesk... 
https://www.data.gov/issue/request-id/13912/

...if global issue is persistant we can re-open

**Comment by philipashlock** [comment]
I also added the persistent bug from Socrata sources to a new issue at https://github.com/GSA/data.gov/issues/714
