### ISSUE TITLE
map preview broken (only on collections?) 

### ISSUE THREAD

**Issue by rebeccawilliams** [GSA/datagov-wptheme#543]
See: https://catalog.data.gov/dataset/usgs-us-topo-map-collection

**Comment by kvuppala** [comment]
@rebeccawilliams looks like issue is with only https link, http works fine http://catalog.data.gov/dataset/usgs-us-topo-map-collection

**Comment by rebeccawilliams** [comment]
@kvuppala ah! Correct. Is this issue being addressed elsewhere?

**Comment by kvuppala** [comment]
@rebeccawilliams 
dont think so, looks like the issue is originating from https://otile1.mqcdn.com/tiles/1.0.0/osm/1/0/0.png, the map tiles are not getting loaded in https because of some ssl issue on the open street map tiles we use.  

The below http url works fine, for https if you open the URL in browser and accept the certificate issue, you will notice that map starts to load in catalog, which is not a good solution for any user.  
http://otile1.mqcdn.com/tiles/1.0.0/osm/1/0/0.png

Not sure if we can reach out to anyone on this, need to see if we should just default to http URLs for map tiles, which might introduce the mixed content issue on the browser.

**Comment by rebeccawilliams** [comment]
@lxbarth, any insight on this?

**Comment by lxbarth** [comment]
@rebeccawilliams - not sure, those are Mapquest tiles. Ping me if you'd like to have an OSM map powered by Mapbox on there :)

**Comment by rebeccawilliams** [comment]
@lxbarth very fair Alex and something we should consider! :)

@kvuppala we should not force the http for the those tiles, see: https://github.com/okfn/recline/commit/6aeec4926659d1a4b5ee014b27a2fd91c83b0f75, I'll close this issue and open it in [/ckanext-geodatagov/](https://github.com/GSA/ckanext-geodatagov/)
