### ISSUE TITLE
Browser security settings prevent links from working within iframes when using SSL

### ISSUE THREAD

**Issue by philipashlock** [GSA/datagov-wptheme#557]
We're currently using an iframe on one topic area, AAPI, which breaks some functionality when the site is accessed via HTTPS and links to insecure URLs are clicked within the iframe. 

We should avoid using iframes here as much as possible and either provide a direct link to the catalog or use a javascript embed or similar solution such as datacatalog.js (#473)

**Comment by kvuppala** [comment]
datacatalog.js gets the dataset list only in a custom theme and it doesn’t displays the full dataset information and also require huge lift to show the search and facet info etc, in order to achieve exact same iframe from catalog to data.gov for AAPI, we would need to implement server side script which will fetch the data on every click.

Now that AAPI is moved away from iframe solution,  we can revisit the embed feature for dataset pages in general.

**Comment by kvuppala** [comment]
i think this issue can be close now that we have moved away from iframe for AAPI data page,  we can create a new issue if anything specific needs to be addressed.
