### ISSUE TITLE
Driving Test Pass Rates

### ISSUE THREAD

**Issue by aslipervez** [GSA/datagov-wptheme#575]
Hi 

I am a student in Massachusetts, and I want to do my driving test sometime this year for a US driving license. I was not able to locate any aggregated data related to pass rates in MA (or nationwide). I'd also be interested in knowing how the data looks for different states in the US, and by gender, month of the year and day of the week.

Thank you

**Comment by rebeccawilliams** [comment]
Hi @aslipervez,

Thanks for reaching out to the Data.gov GitHub site. Due to federalism many datasets are only collected and available via local government contacts. While Data.gov does harvest data from some state and local open data websites, we have no authority, expertise, or way to obtain that data. 

Some places I would recommend reaching out for this information include:
- The [Massachusetts Registry of Motor Vehicles website](https://www.massrmv.com/Feedback.aspx) 
- [Muckrock](https://www.muckrock.com/foi/create/), should you need guidance on how to submit a Massachusetts Freedom of Information Request
- and the [Open Data Stack Exchange](http://opendata.stackexchange.com/)

Good luck!
