### ISSUE TITLE
census harvest source needs to be fixes

### ISSUE THREAD

**Issue by alanswx** [GSA/datagov-wptheme#582]
This should be a WAF collection with the datasets within the collection. Somehow the attached datasets are not inside.
http://catalog.data.gov/harvest/about/address-range-feature-county-based

**Comment by rebeccawilliams** [comment]
Thanks @alanswx!

**Comment by kvuppala** [comment]
@alanswx you are right, the datasets with in the collection are not associated correctly, based on the harvest job reports nothing changed since Sep 2013,  i am running a test in internal environment to clear the current and reharvest, if everything goes well we can do the same in live site.

![eda96e63_o 1](https://cloud.githubusercontent.com/assets/1738764/6308969/bcc4a1c2-b916-11e4-80f6-e699477625f9.png)

**Comment by kvuppala** [comment]
@rebeccawilliams @philipashlock @hkdctol 
Reharvest in test instance works as expected, when can we reharvest this data in live system, once we do this the total dataset count data.gov will drop by another 3221, as these should be under one parent collection record. 

More info on the issue: 
Looks like when the initial job ran the collection record failed to harvest, and then in the subsequent run the collection record was successful, during the process all the child datasets were not associated to the collection record.   This should be a separate issue where the system should not even harvest the child datasets when the collection record is not successful, will create a separate issue to track this after testing the specific scenario in internal test instance.

**Comment by hkdctol** [comment]
@kvuppala Thanks for the explanation.

**Comment by kvuppala** [comment]
@hkdctol are we good to re-harvest this data to show up as a collection, similar issue exists for this as well - http://catalog.data.gov/harvest/current-address-ranges-relationship-file

Once harvested the total dataset count on catalog will drop by apprx 3000 becasue of the collection  association

**Comment by kvuppala** [comment]
@rebeccawilliams 
I am assuming that we are good to harvest them now?  the count might drop by apprx 3000 once everything harvested correctly.

**Comment by rebeccawilliams** [comment]
@alanswx @kvuppala update on this?

**Comment by kvuppala** [comment]
@rebeccawilliams @alanswx 
Looks like the main harvest source reported on this issue is no longer available http://catalog.data.gov/harvest/about/address-range-feature-county-based, any idea if the name was changed?

@rebeccawilliams 
Can we correct the data on this to represent as collection, for this the total count might drop by only 100. 
http://catalog.data.gov/harvest/current-address-ranges-relationship-file

**Comment by hkdctol** [comment]
Closing for now--not sure there is a current issue.
