### ISSUE TITLE
The CSW MaxRecordDefault needs to be bigger than 10 

### ISSUE THREAD

**Issue by rsignell-usgs** [GSA/datagov-wptheme#588]
I was trying to run some tests on the data.gov CSW service, and I couldn't understand why I was only getting back 10 records despite asking for a maximum of 1000.   

Here's an example notebook that illustrates the problem:
http://nbviewer.ipython.org/gist/rsignell-usgs/f5bdb8c13946d22413a7

And the [GetCapabilities Request](http://catalog.data.gov/csw-all?service=CSW&version=2.0.2&request=GetCapabilities) confirms that 

```
<ows:Constraint name="MaxRecordDefault">
<ows:Value>10</ows:Value>
</ows:Constraint>
```

I'm working on automated workflows to assess ocean forecast models using observed data, and I can understand the desire to keep people from bringing down the server with too many requests, but the limit of 10 records maximum cripples the CSW server for real work.

Can the limit please be increased?

**Comment by rsignell-usgs** [comment]
@kalxas, do you have the capability to increase this?

Also, is this the right place to report these type of issues?

**Comment by kalxas** [comment]
Hi @rsignell-usgs 
Yes, this is the right place to report this issue. Thanks for reporting.
I will issue a pull request to change the settings.

Would a max value of 100 work for you?

**Comment by rsignell-usgs** [comment]
@kalxas, I think 100 is problematic.
Could we try 1000 and if you have performance issues, we could back off from there?

**Comment by kvuppala** [comment]
@rsignell-usgs 
If you are using the client API to parse through the results, are you encountering any issues with the current limit of 10.  
In one of the other CKAN CSW installs, having a max limit of 1000 ran into server not responding issues.

**Comment by rsignell-usgs** [comment]
If I search for "salinity" at data.gov, I immediately get back 7,510 datasets.  
Why can't I perform the same search using the CSW API?

Here's my [notebook illustrating the problem](http://nbviewer.ipython.org/gist/rsignell-usgs/f5bdb8c13946d22413a7)

**Comment by FuhuXia** [comment]
with CSW api, I see you got back 15621 datasets, 10 per page. 

```
>>> csw.results['matches']
15621
```

With ckan api, you got 7,510 results, also 10 per page.
`http://catalog.data.gov/api/action/package_search?q=%28salinity%29`

Ckan api support max up to 1000 records per page. CSW support max 10 records per page. We can change the csw server config and give a big max records per page number, say, 100 or 1000, but it really does not matter on the client side, because no matter what, you will need to iterate thru all pages in order to get complete records back.

**Comment by rsignell-usgs** [comment]
@FuhuXia, ah, okay.   Thanks for the tutorial.

By chance do you know or have an example of how I would iterate through the pages using owslib?

**Comment by FuhuXia** [comment]
The csw.results looks like this `{'matches': 15621, 'nextrecord': 11, 'returned': 10}`, so in next request, you can add in `startPosition=11`. Also I recommend always providing `SortBy=Modified` within the request, because I found out sometimes the csw returns records in non-consistent sequence if no sortby given, causing some major headaches when dealing with paginated results.

**Comment by tomkralidis** [comment]
Simple design pattern: https://gist.github.com/tomkralidis/47a8bce9ca8338b66719

**Comment by rsignell-usgs** [comment]
@tomkralidis and @FuhuXia, thanks to your help, I now understand the issue and have a notebook working:
http://nbviewer.ipython.org/gist/rsignell-usgs/64f3ccd39ecb7c69cd18

Closing this because it's not really a problem once you understand this is just a page limit and know how to deal with it.
