### ISSUE TITLE
Create RSS Feed of New Data Sets

### ISSUE THREAD

**Issue by Raseman** [GSA/datagov-wptheme#59]
An RSS feed of new data sets as they are added to Data.gov would allow the public to track new data sets as soon as they are published.

**Comment by JeanneHolm** [comment]
Agree on this as a requirement.  However, we need to test the way this will work with the data.JSON harvesting (and perhaps the geospatial harvesting as well).

**Comment by philipashlock** [comment]
This feature does exist, but it looks like it might be getting polluted or broken by the harvesters because what I see listed for the past day does not look very useful: http://catalog.data.gov/revision/list?format=atom&days=1

There's more documentation at: http://docs.ckan.org/en/ckan-1.3.3/feeds.html

The API is also available to conduct rich filtering and queries like this. We'll see if we can provide options for a filtered RSS version that's more relevant for most users.

**Comment by rossjones** [comment]
Depending on whether data.gov has customised metadata_modified (when it is indexed into Solr) won't the following do the right thing?

http://catalog.data.gov/feeds/custom.atom?q=&sort=metadata_created%20desc

**Comment by rebeccawilliams** [comment]
Closing this issue and combining it with the related #369.
