### ISSUE TITLE
Community Categories Should Be Limited to the Community Being Viewed

### ISSUE THREAD

**Issue by Raseman** [GSA/datagov-wptheme#60]
Currently the community categories sub-section of the navigation shows the categories for every community that a data set is associated with. Instead, the community category area should only show the community categories of the particular community that the user is viewing.

**Comment by JeanneHolm** [comment]
Additional comment from Elizabeth Martin: community/topic categories need to be more visible to help the users find data they are looking for.  "The categories help some users (especially those that tend to browse when trying to find things) in understanding what kinds of things (subcategories) fall within a category. Some of the terms are so broad, that especially with more technical terms, it helps to provide definitions or information of what a term.category means or what is included in that term/category, since sometimes that may not be as apparent to those users who are not familiar with the terminology used or the things studied within a discipline."  This is also related to #71 

Perhaps should bring categories higher up or explore alternative navigation options in the catalog.

**Comment by ErieMeyer** [comment]
Is this a current comment? Site doesn't say "communities" any more, so wondering if this is applicable.

**Comment by JeanneHolm** [comment]
Yes, it's a current comment.

**Comment by JeanneHolm** [comment]
This has been completed.  The terminology throughout the site has been made consistent.  The topics in the catalog now do bring up just the topic referenced.  In one case, "Ecosystem" will bring up that topical area and "Climate ecosystem" brings up a separate one for similarly named items.
