### ISSUE TITLE
Display access level more prominently when not public

### ISSUE THREAD

**Issue by philipashlock** [GSA/datagov-wptheme#606]
As part of the redesign of the dataset page to include more fields from Project Open Data (see #366) we do now display the `accessLevel` field in the heading of the dataset, but this is easy to miss.  Yet when the `accessLevel` is `non-public` or `restricted public` it's important for people to be fully aware of this. There should be a more prominent disclaimer to make it clear that there may never be full direct access to a dataset - as opposed to a dataset with a public `accessLevel` where the file downloads simply have not yet been provided yet.

Note that a dataset with `accessLevel` of "restricted public" should actually have an `accessURL` but probably will not have a `downloadURL`

Two things that should be redesigned here: 
- [x] There should be more of a full width banner disclaimer that makes it impossible to miss that the access level is not public
- [x] The text of the warning message about missing resources should be updated to reflect that resources may never become available. 

Here's an example
![dot-screenshot](https://cloud.githubusercontent.com/assets/183402/6609325/5bf945f4-c826-11e4-8b0b-1a4bee54900e.png)

**Comment by dsmorgan77** [comment]
Howdy! I would like to :+1: this redesign. I know there are number of enhancements to the dataset page that in flight, but would like to request that this change be accelerated in the roadmap, if at all possible. We're receiving feedback from our user community that things are not clearly displayed, and this enhancement will be most helpful in resolving it.

**Comment by philipashlock** [comment]
Here's a mockup that shows how we might highlight this with a disclaimer at the top of the page and a new consolidated Access & Use Information section:

![dataset-page-nonpublic](https://cloud.githubusercontent.com/assets/183402/7280345/f8e3c292-e8ef-11e4-9c5b-e7bfe4f034c6.png)

### Disclaimer

This disclaimer would only appear for an `accessLevel` of `non-public`. It would not display for `restricted public`. This uses the following icon font: [fa-lock](http://fontawesome.io/icon/lock/) (color: `#b85123`) and the [See details](#access-use) hyperlink would point to the new "Access & Use Information" heading with an id of `access-use`. The background color can use the [Bootstrap background helper class](http://getbootstrap.com/css/#helper-classes-backgrounds) `bg-warning`

## Access & Use Information

This section will be the new place to display the access level, license, and rights information. This removes and consolidates the `accessLevel` from under the title and the `license` field from the sidebar. 

### Access Level

The icon font and label for each `accessLevel` would be the following: 

###### `public`: [fa-globe](http://fontawesome.io/icon/globe/) (color: `#4679b2`)

> [Public:](https://project-open-data.cio.gov/v1.1/schema/#accessLevel) This dataset is intended for public access and use.

###### `restricted public` [fa-key](http://fontawesome.io/icon/key/) (color: `#b85123`)

>  [Restricted:](https://project-open-data.cio.gov/v1.1/schema/#accessLevel) This dataset can only be accessed or used under certain conditions. 

###### `non-public` [fa-lock](http://fontawesome.io/icon/lock/) (color: `#b85123`)

>  [Non-public:](https://project-open-data.cio.gov/v1.1/schema/#accessLevel) This dataset is not for public access or use. 

If (and only if) additional information is provided in `rights` the label would including this additional sentence afterward as exemplified in the mockup: 

> Specific details are provided below. 

### License

The font icon is [fa-file-text-o](http://fontawesome.io/icon/file-text-o/) (color: `#474747`)

If the license URL is a common license such as Creative Commons, the license text should be the same as the `<title>` on the Creative Commons landing page, e.g. for CC0 the page title is `Creative 
Commons &mdash; CC0 1.0 Universal` and the text should link to the URL used for the field. 

If the license URL is unique the license text should simply read "See this page for license information" and should link to the URL. 

If this is a Federal dataset and no license URL is provided the license text should be: 

> No license information was provided. If this work was prepared by an officer or employee of the United States government as part of that person's official duties it is considered a [U.S. Government Work](http://www.usa.gov/publicdomain/label/1.0/). 

If this is a non-federal dataset and no license URL is provided the license text should be: 

> No license information was provided.

### Rights

Additional information included in the `rights` field would be shown below the `accessLevel` and `license` section as exemplified in the mockup. 

## Downloads & Resources

If this is a dataset with an `accessLevel` of `non-public` then no `distribution` should be displayed whatsoever regardless of whether anything has been provided in the metadata. The only reason why the Downloads & Resources section should ever be rendered for a `non-public` dataset is if a publicly accessible (e.g. not on an intranet) `landingPage` has been provided. If this happens there should be a sentence directly under the Downloads & Resources heading that states: 

> No file downloads are available because this is not a public dataset. See Access & Use Information for details.

**Comment by kvuppala** [comment]
@philipashlock 

If the license URL is a common license such as Creative Commons, the license text should be the same as the <title> on the Creative Commons landing page, e.g. for CC0 the page title is Creative Commons &mdash; CC0 1.0 Universal and the text should link to the URL used for the field.
>> On the above requirement, I think you meant that any license CKAN / Data.gov identifies goes with the above display, for example all the below values would fall under this scenario: 
cc-by, Creative Commons Attribution, https://creativecommons.org/licenses/by/4.0
cc-by-sa, Creative Commons Attribution Share-Alike, https://creativecommons.org/licenses/by-sa/4.0
cc-zero, Creative Commons CCZero, http://creativecommons.org/publicdomain/zero/1.0/
cc-nc, Creative Commons Non-Commercial (Any), https://creativecommons.org/licenses/by-nc/4.0
gfdl, GNU Free Documentation License, http://www.gnu.org/copyleft/fdl.html
odc-by, Open Data Commons Attribution License, http://opendatacommons.org/licenses/by/1-0/
odc-odbl, Open Data Commons Open Database License (ODbL), http://opendatacommons.org/licenses/odbl/
odc-pddl, Open Data Commons Public Domain Dedication and License (PDDL), http://opendatacommons.org/licenses/pddl/
other-at, Other (Attribution), https://project-open-data.cio.gov/unknown-license/#v1-legacy/other-at
other-nc, Other (Non-Commercial), https://project-open-data.cio.gov/unknown-license/#v1-legacy/other-nc
other-closed, Other (Not Open), https://project-open-data.cio.gov/unknown-license/#v1-legacy/other-closed
other-open, Other (Open), https://project-open-data.cio.gov/unknown-license/#v1-legacy/other-open
other-pd, Other (Public Domain), http://creativecommons.org/publicdomain/mark/1.0/other-pd
uk-ogl, UK Open Government Licence (OGL), http://www.nationalarchives.gov.uk/doc/open-government-licence/version/3/


If the license URL is unique the license text should simply read "See this page for license information" and should link to the URL. 
>> Here if the license URL is not in the known defined list that CKAN/Data.gov recognizes, we simply give the text "See this page for license information" and link to the license URL provided in the dataset

**Comment by kvuppala** [comment]
@philipashlock 

If the license URL is a common license such as Creative Commons, the license text should be the same as the <title> on the Creative Commons landing page, e.g. for CC0 the page title is Creative Commons &mdash; CC0 1.0 Universal and the text should link to the URL used for the field.

>>> On the above requirement, I think you meant that any license CKAN / Data.gov identifies goes with the above display, for example all the below values would fall under this scenario: 

cc-by, Creative Commons Attribution, https://creativecommons.org/licenses/by/4.0
cc-by-sa, Creative Commons Attribution Share-Alike, https://creativecommons.org/licenses/by-sa/4.0
cc-zero, Creative Commons CCZero, http://creativecommons.org/publicdomain/zero/1.0/
cc-nc, Creative Commons Non-Commercial (Any), https://creativecommons.org/licenses/by-nc/4.0
gfdl, GNU Free Documentation License, http://www.gnu.org/copyleft/fdl.html
odc-by, Open Data Commons Attribution License, http://opendatacommons.org/licenses/by/1-0/
odc-odbl, Open Data Commons Open Database License (ODbL), http://opendatacommons.org/licenses/odbl/
odc-pddl, Open Data Commons Public Domain Dedication and License (PDDL), http://opendatacommons.org/licenses/pddl/
other-at, Other (Attribution), https://project-open-data.cio.gov/unknown-license/#v1-legacy/other-at
other-nc, Other (Non-Commercial), https://project-open-data.cio.gov/unknown-license/#v1-legacy/other-nc
other-closed, Other (Not Open), https://project-open-data.cio.gov/unknown-license/#v1-legacy/other-closed
other-open, Other (Open), https://project-open-data.cio.gov/unknown-license/#v1-legacy/other-open
other-pd, Other (Public Domain), http://creativecommons.org/publicdomain/mark/1.0/other-pd
uk-ogl, UK Open Government Licence (OGL), http://www.nationalarchives.gov.uk/doc/open-government-licence/version/3/

**Comment by kvuppala** [comment]
this is complete, see the sample below links which shows the required behavior
http://catalog.data.gov/dataset/110a-inspector-credentials
http://catalog.data.gov/dataset/831-files

**Comment by philipashlock** [comment]
@kvuppala it doesn't look like the [second example listed](http://catalog.data.gov/dataset/831-files) has the expected behavior for the license field.

**Comment by kvuppala** [comment]
@philipashlock In the above federal dataset case should we be displaying the license information similar to the non federal data which doesnt provide license info? for ex: http://catalog.data.gov/dataset/national-park-boundariesf0a4c

**Comment by kvuppala** [comment]
@philipashlock I think you are referring to the below block for federal datasets without license,  we will see what is going on here:

If this is a Federal dataset and no license URL is provided the license text should be:

```
No license information was provided. If this work was prepared by an officer or employee of the United States government as part of that person's official duties it is considered a U.S. Government Work.
```

**Comment by philipashlock** [comment]
@kvuppala correct. Since it's a federal dataset it should include the full text and link

**Comment by kvuppala** [comment]
@philipashlock @hyoon @FuhuXia 

I know why there is change in behavior for data.json harvested data, here are more details on this. 

The right license text is displayed for federal geospatial datasets where license information is not provided, this is due to the fact that during geospatial harvesting the CKAN license value is mapped to a null value
for example:
http://catalog.data.gov/dataset/02031-chrp-500-geophysical-surveys-of-bear-lake-utah-idaho-september-2002-shot-point-navigati
http://catalog.data.gov/dataset/02031-chrp-sol-geophysical-surveys-of-bear-lake-utah-idaho-september-2002-seismic-navigation-s
http://catalog.data.gov/dataset/111th-congressional-districts-and-zip-code-tabulation-areas (old DMS migrated data without any license value) 

In the case of data.json harvesting, when the license value is not provided at all, CKAN license value is mapped to "License Not Specified" instead of null as done in the geospatial harvesting side. 
for example: 
http://catalog.data.gov/dataset/aquatic-plant-and-waterfowl-habitat-survey-1988-stillwater-wildlife-management-area-and-vi
http://catalog.data.gov/dataset/mariner-oversight-data

In the dataset UI page, we are treating the null value different than "License Not Specified" value,  where as both should have been considered same and displayed with the standard no license language "No license information was provided. If this work was prepared by an officer or employee of the United States government as part of that person's official duties it is considered a U.S. Government Work.", with only one exception to this would be that data.json metadata has a license URL which is unique and doesn't map to any common licenses identified.   In case of unique license URL we display the language "See this page for license information",  this case is working fine as we can see here  (in these cases since license is provided and could not be mapped to a common license the CKAN core license field is left as null ):
for example: 
http://catalog.data.gov/dataset/1987-toxics-release-inventory-data-for-puerto-rico
http://catalog.data.gov/dataset/1987-toxics-release-inventory-data-for-guam

Pending Actions to resolve the differences:
- Should we align both geospatial harvesting and data.json harvesting to store the license value as "No License Specified" when not provided (**option A**) ,  and treat this same as the license value "null" and display the standard language with the unique license URL exception?   We can also store the license value as "null"  (**option B**) when not provided, but we wont be able to differentiate between the unique license URLs with not specified ones until we look at the extra attribute for license URL
- if we go with "null" value as the standard on both cases above, we can do an API update to reflect the right value across all data.json datasets to show the right standard language, if we want to stick with the "License Not Specified" value when only not provided, we need to need to sync the geospatial and non-geospatial harvesters code and template change to display the standard language (will require a code push to production for next release).

Also last night we udpated all schema 1.1 data.json records to map to the right CKAN core license field from the license URL value that is in the extras attributes, thats when we are seeing this License Not Specified more often than general.

Please suggest which option (**A or B**) to implement to resolve the issue.

**Comment by philipashlock** [comment]
Let's go with **option A** so that null or missing values from any source metadata is mapped to "No License Specified" and then use that to trigger the no license language in the UI. 

Let's also have a new CKAN license value to map to for unique URL's and any other non-standard license we might get. This could be called "Other License Specified"  Then we'd used that to trigger the link and language of "See this page for license information" and pull from the extra field.

**Comment by kvuppala** [comment]
@philipashlock @ykhadilkar-rei @FuhuXia 
Thanks Phil, by reviewing all the field mappings for geospatial data sources looks like for the geospatial FGDC/ISO sources we don't have any mapping to the license field, hence we will leave them as null since "No License Specified" would indicate we are looking for something in the metadata.  

For UI purposes null / "No License Specified" would be treated the same, hence standard language will appear. 

Once we finalize a mapping for geospatial sources, we can do the necessary data updates, we avoided update now given that all million datasets including the ones in collection will be updated if we go as stated earlier.

**Comment by kvuppala** [comment]
Option A as detailed above is completed with the consideration of the latest comment https://github.com/GSA/data.gov/issues/606#issuecomment-105661282
