### ISSUE TITLE
Map viewer reports "can not load map" for this WMS service

### ISSUE THREAD

**Issue by rsignell-usgs** [GSA/datagov-wptheme#621]
We have a model output  dataset from a Unidata THREDDS Data Server  at
http://catalog.data.gov/dataset/coawst-forecast-system-usgs-us-east-coast-and-gulf-of-mexico-experimental

If you click any of the WMS links (simple or advanced viewer) we get back "can not load map":
![4-23-2015 1-55-42 pm](https://cloud.githubusercontent.com/assets/1872600/7318782/869770fc-ea5d-11e4-9feb-3ec3948375af.png)

Yet it seems that the WMS service is working okay.  This request:
http://geoport-dev.whoi.edu/thredds/wms/coawst_4/use/fmrc/coawst_4_use_best.ncd?LAYERS=temp&ELEVATION=-0.03125&TIME=2015-04-24T00%3A00%3A00.000Z&TRANSPARENT=true&STYLES=boxfill%2Frainbow&CRS=EPSG%3A4326&COLORSCALERANGE=0%2C30&NUMCOLORBANDS=64&LOGSCALE=false&SERVICE=WMS&VERSION=1.1.1&REQUEST=GetMap&EXCEPTIONS=application%2Fvnd.ogc.se_inimage&FORMAT=image%2Fpng&SRS=EPSG%3A4326&BBOX=-83.006379190914,31.242026011357,-58.757973988643,55.490431213629&WIDTH=256&HEIGHT=256
produces the image here:
![coawst_4_use_best](https://cloud.githubusercontent.com/assets/1872600/7318832/eeaa8b0c-ea5d-11e4-8bcc-e8ed23df9f18.png)

There are lots of model output datasets served via THREDDS, so it would be great to figure out how to display something useful from the WMS service in the map viewer.   I've raised the issue on the map viewer repo here: https://github.com/chilukey/viewer/issues/1

**Comment by rsignell-usgs** [comment]
@kvuppala, I'm wondering if there is another way to pursue issues with the viewer application.  It seems that https://github.com/chilukey hasn't been seen on github for over two years, and there are no other contributors listed on the viewer project, so it seems issues like https://github.com/chilukey/viewer/issues/1 are going to go unaddressed.

You said the viewer  was a GMU effort?  
Is there perhaps someone else I can contact at GMU?

**Comment by rsignell-usgs** [comment]
This is now working!   @chilukey had to bump the size limit for the GetCapabilities because this one is big -- it contains thousands of timestamps.  Here's proof it's working in the Advanced Viewer:
![5-4-2015 9-18-07 am](https://cloud.githubusercontent.com/assets/1872600/7454265/ee7f97a0-f23f-11e4-952b-7417034ba386.png)

**Comment by rsignell-usgs** [comment]
@chilukey, I'm opening this again because _today_ I'm getting `cannot load map` again.  :crying_cat_face:

**Comment by kliu4** [comment]
Hi Rich,

Thanks for the report, I think the instability is caused by the network
from viewer server to the map service host. So it is urgent to upload the
cachstore to save such 'big' services. Fortunately, I have set up embedded
database in viewer and hope to finish it soon.

On Tue, May 5, 2015 at 2:06 PM, Rich Signell notifications@github.com
wrote:

> @chilukey https://github.com/chilukey, I'm opening this again because
> _today_ I'm getting cannot load map again. [image: :crying_cat_face:]
> 
> —
> Reply to this email directly or view it on GitHub
> https://github.com/GSA/data.gov/issues/621#issuecomment-99161386.

## 

Kai Liu
Ph.D. student
Department of Geography and GeoInformation Science
George Mason University

**Comment by rsignell-usgs** [comment]
@chilukey , what is your plan for caching?
Please be advised that the getCapabilities for this dataset changes every day because it's a forecast model.   Will you update the cache once a day?

**Comment by kliu4** [comment]
oops, this is a problem. the getCapabilities file of this WMS will change
every day. Probably we still need to load the capabilities file every time
instead of using cache.

On Tue, May 5, 2015 at 2:36 PM, Rich Signell notifications@github.com
wrote:

> @chilukey https://github.com/chilukey , what is your plan for caching?
> Please be advised that the getCapabilities for this dataset changes every
> day because it's a forecast model. Will you update the cache once a day?
> 
> —
> Reply to this email directly or view it on GitHub
> https://github.com/GSA/data.gov/issues/621#issuecomment-99173255.

## 

Kai Liu
Ph.D. student
Department of Geography and GeoInformation Science
George Mason University

**Comment by rsignell-usgs** [comment]
Caching would still help tremendously.   It's just that the cache would have to be updated once a day.

**Comment by rsignell-usgs** [comment]
@chilukey, it's strange that the WMS on this dataset worked a week ago, but hasn't worked since.   I've tried it dozens of times.  Are you sure there isn't some other kind of problem other than "instability is caused by the network from viewer server to the map service host"?

**Comment by kliu4** [comment]
Hi Rich, I switched to use another method to get the response of
getcapabilities file last week. Probably it has some performance issue to
fetch the response body and caused "can not load map". That is why it
worked a week ago and has worked since. I optimized it just now, and the
link should work now:

http://199.26.254.190:8088/viewer/?url=http%3A%2F%2Fgeoport-dev.whoi.edu%2Fthredds%2Fwms%2Fcoawst_4%2Fuse%2Ffmrc%2Fcoawst_4_use_best.ncd%3Fservice%3DWMS%26version%3D1.3.0%26request%3DGetCapabilities&serviceType=WMS

On Mon, May 11, 2015 at 1:59 PM, Rich Signell notifications@github.com
wrote:

> @chilukey https://github.com/chilukey, it's strange that the WMS on
> this dataset worked a week ago, but hasn't worked since. I've tried it
> dozens of times. Are you sure there isn't some other kind of problem other
> than "instability is caused by the network from viewer server to the map
> service host"?
> 
> —
> Reply to this email directly or view it on GitHub
> https://github.com/GSA/data.gov/issues/621#issuecomment-100999391.

## 

Kai Liu
Ph.D. student
Department of Geography and GeoInformation Science
George Mason University

**Comment by rsignell-usgs** [comment]
@chilukey, Is it working for you?  I still get "can not load map".

**Comment by kliu4** [comment]
Yes, it works for me, taking about 30 seconds to show the map. In my local
version using cache, the time can be shorter than 10 seconds, however, the
version still needs to be tested.

On Mon, May 11, 2015 at 5:28 PM, Rich Signell notifications@github.com
wrote:

> @chilukey https://github.com/chilukey, Is it working for you? I still
> get "can not load map".
> 
> —
> Reply to this email directly or view it on GitHub
> https://github.com/GSA/data.gov/issues/621#issuecomment-101052412.

## 

Kai Liu
Ph.D. student
Department of Geography and GeoInformation Science
George Mason University

**Comment by JJediny** [comment]
See #623 for continued discussion spatial viewer
