### ISSUE TITLE
Create Method to Group Subsets of Data Into Master Data Sets 

### ISSUE THREAD

**Issue by Raseman** [GSA/datagov-wptheme#63]
It would make search, browsing, discovery, and navigation much easier if data sets that are subsets of a larger dataset could be collapsed into master records. For examples, the EPA's Toxics Release Inventory data sets are currently listed separately for each place X year.

**Comment by JeanneHolm** [comment]
I think this was accomplished in the CKAN migration earlier this year with data collections.  Can you describe more or provide a screen shot?

**Comment by philipashlock** [comment]
The feature does exist in CKAN, but only seems to be used by geospatial datasets so far. It looks like there are only about 100 collections: https://www.google.com/search?q="This+dataset+is+a+collection+of+other+datasets."+site%3Acatalog.data.gov

I think the real issue here is establishing a method to leverage the collections feature when publishing the data.json metadata.

**Comment by cew821** [comment]
It seems to me that if you are listing different years of the same series of data as separate datasets then you are Doing it Wrong. That is one data asset, and should have one record in the catalog. EIA in Energy is guilty of this and I'm working to collapse these into a single entry referencing the site where one can pick whatever year they want, and an API of the same.

**Comment by philipashlock** [comment]
For the most part I agree with you @cew821 but there are many cases where the year doesn't just denote the year the data was collected, but all sorts of things that were done differently that year such as the naming of fields or other differences in metadata that couldn't simply be merged from one year to the next. 

Additionally, it's often helpful to have options to download sections of a very large dataset, such as per year. 

Part of the intent of Project Open Data is to be more clear and consistent that metadata on data.gov and referenced by data.json files should always point directly to the raw data, not an intermediary html page or form that you need to go through in order to access the data. Since CKAN provides the capability of grouping datasets in a series already, I don't see any reason why we should point to an intermediary step the makes it more difficult to access the raw data directly.

**Comment by Raseman** [comment]
Any update on this? This seems like a big one for improving data set discovery and search to me. Could we have some ability to "Group (or hide) similar results" similar to search engines like Google or Westlaw etc.? Would not have to rely on agencies doing it exactly right in their data.json catalogs.

**Comment by JeanneHolm** [comment]
Much of this had already been accomplished in creating "collections" within CKAN as @philipashlock notes above. Earlier this year users searched through 400,000+ datasets, but these are now managed in ~88,000 collections that include the related items for that dataset.  With the data.JSON files, this needs to be reworked a bit as the native JSON files are not necessarily keeping those collections as such.  

The "group or hide similar" idea is good, will have to check into whether CKAN provides something or we can contribute code to do so.

**Comment by philipashlock** [comment]
We already support this as part of the CKAN platform, but this needs to be supported as part of the Project Open Data schema and that will be coming as part of the next version of the schema. See https://github.com/project-open-data/project-open-data.github.io/issues/258

**Comment by hkdctol** [comment]
Seems to be addressed by collections in CKAN.
