### ISSUE TITLE
Housing Counselor Finder webservice API for HUD Disclosures **UNAVAILABLE**

### ISSUE THREAD

**Issue by robert-harrington** [GSA/datagov-wptheme#646]
To whom it may concern:

Housing counselor webservice API appears to be down it is not returning any data when it is called.

Please provide a status of when it will become available ASAP.

**Comment by ErieMeyer** [comment]
Hey Robert,

Can you show me the link where the webservice API is? Trying to track this down for you. 

cc @gbinal

**Comment by ErieMeyer** [comment]
Found it: http://data.hud.gov/housing_counseling.html

@gbinal -- can you add this to the API area on data.gov? Also -- it's extremely confusing on how to find APIs here.

I'm also emailing the data.gov contact for this type of data, george.h.grotheer@hud.gov

**Comment by robert-harrington** [comment]
It appears the service has been restored. The data we pull from is located at this page: http://data.hud.gov/housing_counseling_form.html 

Any idea why this outage occurred? or could it have been scheduled maintenance?

**Comment by rebeccawilliams** [comment]
Thanks @robert-harrington!

It doesn't look like this data is cataloged on Data.gov yet, which is worth flagging here! 

#### Direct Contact is Best

For emergencies the best route is contacting the Dataset Maintainer directly. This information is included for every federal dataset that _is_ cataloged on Data.gov. If it's not cataloged on Data.gov yet, find the closest contact. Here, from the API docs, it looks like it is: Housing.counseling@hud.gov 

#### Report Data Missing from Data.gov and Data Issues to Open Data Leads

For open data questions about HUD data please flag: stanley.a.buch@hud.gov & webmanager@hud.gov; I got that info via: http://labs.data.gov/dashboard/offices/detail/49023/2015-02-28; @ErieMeyer see also #629 for these how contacts can better be displayed on the dataset page. 

For reporting issues on data on Data.gov see also the new `Report Data Issue` Button on every dataset page and www.data.gov/issue. The more information you include, the easier it is for us to fwd it along to the contacts listed above. 

#### Finding APIs on Data.gov
- The Data.gov API info is at www.data.gov/developers
- For all other APIs, you should search via the main catalog. You can search by format on the sidebar or simply for the dataset name and all available formats are listed will be listed on the dataset page. If an agency doesn't have a dataset listed please report it! If they have a dataset listed, but it's not listed as an API report it! I cannot emphasize how much direct contact reporting can help the catalog. 

I have reported this missing dataset, you can track that issue here: http://www.data.gov/issue/request-id/6522/

Glad the API is back up and running! 

Closing this issue here.
