### ISSUE TITLE
Broken links

### ISSUE THREAD

**Issue by kevin-cutress-wcsc** [GSA/datagov-wptheme#657]
Who do we contact about broken links.    The following links are broken

http://catalog.data.gov/dataset/total-tonnage-of-commodites-carried-on-commercial-waterways-by-traffic-type

and

http://catalog.data.gov/dataset/total-tonnage-foreign-and-domestic-of-commodites-carried-on-commercial-waterways

They both refer to an internal website not our public site.

**Comment by rebeccawilliams** [comment]
Thanks for reporting! All data URLs are maintained by the agency itself rather than Data.gov. You can find maintainer contact information in the metadata of each dataset on Data.gov. 

![screen shot 2015-07-03 at 3 41 19 pm](https://cloud.githubusercontent.com/assets/1725454/8504150/1247dd26-219a-11e5-955b-c5eb20eb9df2.png)

The contact for both of these datasets =

> Maintainer: Kevin Cutress
> Maintainer Email: amy.c.tujague@usace.army.mil

I also reported this issue via the Data.gov Help Desk: 

![screen shot 2015-07-03 at 3 36 43 pm](https://cloud.githubusercontent.com/assets/1725454/8504137/9c4d20ae-2199-11e5-8ced-1a15d633e475.png)

Once approved, you will be able to track progress on the Issue here: https://www.data.gov/issues/

**Comment by kevin-cutress-wcsc** [comment]
‎I am with the agency that has the data but the URL itself has changed. Server has been moved to a contractor system and we can't make the old URL point to the contractors server. The URL needs to be changed on the data.gov site

Sent from my BlackBerry 10 smartphone on the Verizon Wireless 4G LTE network.
From: Rebecca Williams
Sent: Friday, July 3, 2015 2:43 PM
To: GSA/data.gov
Reply To: GSA/data.gov
Cc: Cutress, Kevin P MVN
Subject: [EXTERNAL] Re: [data.gov] Broken links (#657)

Thanks for reporting! All data URLs are maintained by the agency itself rather than Data.gov. You can find maintainer contact information in the metadata of each dataset on Data.gov.

[screen shot 2015-07-03 at 3 41 19 pm]https://cloud.githubusercontent.com/assets/1725454/8504150/1247dd26-219a-11e5-955b-c5eb20eb9df2.png

The contact for both of these datasets =

Maintainer: Kevin Cutress
Maintainer Email: amy.c.tujague@usace.army.milmailto:amy.c.tujague@usace.army.mil

I also reported this issue via the Data.gov Help Desk:

[screen shot 2015-07-03 at 3 36 43 pm]https://cloud.githubusercontent.com/assets/1725454/8504137/9c4d20ae-2199-11e5-8ced-1a15d633e475.png

Once approved, you will be able to track progress on the Issue here: https://www.data.gov/issues/

**Comment by rebeccawilliams** [comment]
Ahh! See under Human Capital: http://labs.data.gov/dashboard/offices/detail/49229/2015-02-28

> Open Data Primary Point of Contact: william.erwin@osd.mil

should be able to update the harvest source.
