### ISSUE TITLE
display dataset topic categories on dataset page, mockup attached

### ISSUE THREAD

**Issue by kvuppala** [GSA/datagov-wptheme#658]
Currently topics and topic categories are available on the main datasets landing page, organization, group pages, below are the corresponding URLs. 
http://catalog.data.gov/dataset
http://catalog.data.gov/organization/nasa-gov
http://catalog.data.gov/group/climate5434

However on the dataset page http://catalog.data.gov/dataset/u-s-hourly-precipitation-data only topics are displayed, but topic categories are visible to the end users, below mockup addresses the display of topics categories for each of the topics listed in the dataset page. 

![topic_category-display_expandable](https://cloud.githubusercontent.com/assets/1738764/8527205/767f3adc-23d9-11e5-9c65-169a7ba26fc3.png)

How it works:
1. Under the Topics section currently all the associated topics are displayed
2. In the new mockup, when a topic has topic category an expandable icon (+) will be displayed, clicking on that will display all the associated topic categories, one category in a separate line
3. Clicking on the (-) will collapse the categories for that selected topic
4. When a topic doesn't have any topic categories associated, no +/- icon will be displayed.

**Comment by Kapil-bulchandani** [comment]
Attach is the screenshot for the implementation
![screen shot 2015-07-16 at 3 13 54 pm](https://cloud.githubusercontent.com/assets/2903623/8732848/0d5eb76a-2bce-11e5-8b23-47c2958d9325.png)
Since the topic names were already links therefore hover over functionality is added to show the topic categories. clicking on topic category takes to the corresponding group with the given category filter

**Comment by kvuppala** [comment]
Functionality is deployed in production and can be reviewed on this sample dataset - http://catalog.data.gov/dataset/u-s-hourly-precipitation-data
