### ISSUE TITLE
Display custom sub-organization logos based on publisher or bureauCode

### ISSUE THREAD

**Issue by philipashlock** [GSA/datagov-wptheme#663]
We could use key/value extras on the organization to provide logo image URLs for each department's bureauCode or publisher field.

**Comment by kvuppala** [comment]
@philipashlock 
Do we want to replace the current organization log with the sub-organization logo, or should we accommodate both in the template?

http://catalog.data.gov/dataset/high-specific-power-multiple-cylinder-alpha-free-piston-stirling-engine-project

**Comment by kvuppala** [comment]
@philipashlock @hkdctol 
The feature is deployed as of last night, currently there wont be any change as we  have  not placed any bureau logos in  the production catalog.   

Below is how it works : 
- If any bureau wants their logo to be displayed, all we  need to do it place the bureau logo with the file name convention (xxx-yy.png, or xxx-yy.jpg, or xxx-yy.gif) in github https://github.com/GSA/ckanext-datagovtheme/tree/master/ckanext/datagovtheme/fanstatic_library/images/logos , and  push the files  to  production 
- Once the logo file is place, any dataset in catalog which has the matching  bureauCode field will  show the corresponding bureau logo and  bureau name ( as listed in the https://project-open-data.cio.gov/data/omb_bureau_codes.csv) 
- The bureau logo and  bureau name , will replace the currently displayed organization name  and logo, also the link on the bureau logo will  take the user to the dataset page with the query filtered to that specific bureau code.

Since  the production site doesnt have any logo files, below are some  examples from UAT catalog:

http://uat-catalog-fe-data.reisys.com/dataset/forest-inventory-and-analysis-database   005:96
http://uat-catalog-fe-data.reisys.com/dataset/bea-itables 006:08
http://uat-catalog-fe-data.reisys.com/dataset/2010-2017-defense-logistics-agency-strategic-plan-131cd  007:15
http://uat-catalog-fe-data.reisys.com/dataset/12-28-2002-clarence-cannon-nwr-christmas-bird-count   010:18
http://uat-catalog-fe-data.reisys.com/dataset/110a-inspector-credentials 021:12
http://uat-catalog-fe-data.reisys.com/dataset/2009-report-to-congress-on-white-house-staff 100:05
