### ISSUE TITLE
Use of Data.gov data

### ISSUE THREAD

**Issue by ghost** [GSA/datagov-wptheme#735]
Hi All
I just had query if I can use data.gov data for commercial purposes outside the United States.Example  Canada
Thanks,
Neil

**Comment by hkdctol** [comment]
On every dataset page, see the Access & Use section for that dataset. For most federal datasets, they are US Government work: https://www.usa.gov/government-works
Since you can access many state/local datasets on Data.gov, check the access & use section to find the link to the terms that apply to that jurisdiction's datasets.

**Comment by ghost** [comment]
@hkdctol Thank you for your reply Madam

**Comment by ghost** [comment]
@hkdctol I have emailed you on a specific question
