### ISSUE TITLE
Alternatives to Google Geocharts on Open Gov page

### ISSUE THREAD

**Issue by JJediny** [GSA/datagov-wptheme#740]
https://www.data.gov/open-gov/

Using google geocharts seems functional for now. Though Geocharts doesn't support US counties - if we wanted to improve it would be to use a combination of csv and topojson and D3 for visualization?

Topojson over geojson as it takes a US Counties file from hundreds of MB (even simplified geojson file) down to 2.7MB and using the CSV to match by field name on the fly so we'd only have to maintain the CSV.

**References**
https://gist.github.com/JJediny/bf3fa74147c44f13d05e347a9f20f9a2
http://mapshaper.org/

**Comment by hkdctol** [comment]
Would this take much effort? Having the maps doesn't seem that compelling, and we should think about what should be on this page in general.

**Comment by JJediny** [comment]
@hkdctol agree that it is not top priority, however the current map is inaccurate in reflecting counties/cities. If done well it could be updated to reflect a more accurate geographic representation and provide an opportunity to provide a more accurate status dashboard of States/Counties/Cities Open Data platforms federating up through Data.gov

**Comment by JJediny** [comment]
@hkdctol @philipashlock @kvuppala This would make a good substitute as all it needs the url to a GeoJSON file which we could add to a repo in github

https://github.com/bmcbride/geojson-share-maps

Example:
https://bmcbride.github.io/geojson-share-maps/?src=https://d2ad6b4ur7yvpq.cloudfront.net/naturalearth-3.3.0/ne_110m_admin_1_states_provinces_shp.geojson&logo=https://upload.wikimedia.org/wikipedia/en/thumb/a/a4/Flag_of_the_United_States.svg/320px-Flag_of_the_United_States.svg.png&fields=name,name_alt,adm1_code,region,wikipedia&title=US%20States&attribution=States%20courtesy%20of%20geojson.xyz

**Comment by John123Yu** [comment]
Hi I've started working on this. I've converted the CSV files to geojson and have been gathering coordinates and polygon geometry values for each feature. Currently with the bmcbride version, it looks like this: 

https://bmcbride.github.io/geojson-share-maps/?src=https://rawgit.com/John123Yu/LeafletMapDataGov/master/GovMap.geojson

I'm am still gathering more coordinates but the international and states have been mostly completed.

However I have also been researching leaflet.js, a popular javascript mapping library. If you clone this repo: 

https://github.com/John123Yu/LeafletMapDataGov

And open the Map.html page on ur browser, you can see the current working version. I've found the leaflet.js version to be more customizable. You can add automatic redirects upon clicking a feature and mouseover, mouseout, right-click actions. You can also style (colors, shade, etc) different features (states, international, local) differently, which I'm not quite sure you can with the bmcbride version. 

Another feature I want to start working on is layers, which default shows all three geojson datas, but also allows the user to click and choose to display only state data for example. This can be useful because state and county features will overlap.

Lastly the mcbride version has a search feature at the moment. But I believe I can add a search for the leaflet version also. 

Anyways, these are just some suggestions, please take a look at each and let me know if anything can work with the site.

**Comment by kvuppala** [comment]
@John123Yu Thank you for updates.

@JJediny let me know your feedback and suggestion?

**Comment by John123Yu** [comment]
Hey everyone, I uploaded the latest version of leaflet map onto github pages. 

https://john123yu.github.io/LeafletMapDataGov/

Please take a look and feel free to offer any comments or suggestions on features, styling, design, additional features etc. 

I tried making this map similar to the old Geocharts in terms of the mouse hover and mouse click functionality. 

@JJediny also directed me to other maps/github links which used some cool pluggins that I also incorporated. 

The geoJson data has been populated with coordinates. 

This is the bmcbride version: 
https://bmcbride.github.io/geojson-share-maps/?src=https://rawgit.com/John123Yu/LeafletMapDataGov/master/GovMap.geojson

**Comment by kvuppala** [comment]
https://www.data.gov/open-gov/ is launched with a Map View of the open data sites.
