### ISSUE TITLE
CKAN metrics/GA integration with CKAN 2.3

### ISSUE THREAD

**Issue by kvuppala** [GSA/datagov-wptheme#790]
Currently Catalog.data.gov has only broken link report and the current repo is https://github.com/GSA/ckanext-report/tree/2.3-upgrade 

Look into other reports offered on the below, and study the feasibility of enabling them on catalog.data.gov 
https://github.com/datagovuk/ckanext-report
https://github.com/datagovuk/ckanext-ga-report

**Comment by John123Yu** [comment]
@JJediny @kvuppala @hkdctol @philipashlock 

Hey as per this morning's meeting, I've been looking for different analytics extensions. It does appear that the ckanext-ga-report extension is the best one available. There is a stat analytics extension: http://docs.ckan.org/en/latest/maintaining/stats.html that provides limited information. Click the link to get an overview of what it provides. 

It appears that the main google analytics extensions are:
    -https://github.com/ckan/ckanext-googleanalytics
    -https://github.com/datagovuk/ckanext-ga-report
I was not able to find any other google analytics ckan extensions.

I believe we are already using the ckanext-googleanalytics extension. The ckanext-ga-report will add additional information, especially those that will give insight to users. Here's what the README for ckanext-ga-report says:

"Whereas ckanext-googleanalytics focusses on providing page view stats a recent period and for all time (aimed at end users), ckanext-ga-report is more interested in building regular periodic reports (more for site managers to monitor)."

The ckanext-ga-report allows access to google analytics information, and this metrics/dimensions page provides documentation on what information can be queried/accessed:

https://developers.google.com/analytics/devguides/reporting/core/dimsmets

With that said, the analytics being downloaded by the ckanext-ga-report has not been updated in 3 years. Some of the metrics being queried through the API have been deprecated. In that same time, google analytics has also added new metrics and dimensions that can be queried. I will spend time reading through the documentation on additional metrics that we can add. These metrics will be of use to catalog.data.gov users and ourselves. I will provide updates as I work through them.

**Comment by John123Yu** [comment]
I just wanted to provide an update on the current status of this extension. I've updated the dimensions and metrics that we can query from the GA API; however, I will probably go back later to double check the queries and add a couple more metrics and dimensions.

Currently I have all the tables displayed on one page, but I will separate them into individual tabs later on. Here is what the site-usage page currently looks like:

![screencapture-192-168-56-101-data-site-usage-1502204307759](https://user-images.githubusercontent.com/22822738/29079069-2a5907d6-7c2a-11e7-8eee-644414c318d4.png)
![screencapture-192-168-56-101-data-site-usage-1502204307759-2](https://user-images.githubusercontent.com/22822738/29079071-2b3155dc-7c2a-11e7-85e7-f59591495109.png)


I am currently working on implementing charts. Here is a template barchart I've created so far. 

https://john123yu.github.io/D3-BarChart/

Yesterday I was able to implement the bar chart with actual GA data into my local CKAN site. I will be working to implement this barchart with the remaining tables and to fix formatting issues. I will also be creating a pie chart for tables that use percentages instead of raw numbers. 

It is still early so please feel free to provide feedback on formatting, style, design, types of charts, metrics and dimensions etc.

**Comment by John123Yu** [comment]
@JJediny @kvuppala @hkdctol @philipashlock 

Here is the current state of the ga-report extension. Please take a look and feedback would be appreciated. There are still many details to fix and improve upon. 

http://34.226.152.211/data/site-usage

**Comment by JJediny** [comment]
@John123Yu @kvuppala lets ship it as soon as we can

**Comment by John123Yu** [comment]
@JJediny @kvuppala @hkdctol @philipashlock

GA report extension is now on BSP Dev. It is working well with Chrome, but there are some bugs with internet explorer which I will resolve later. It has the latest changes we discussed during the meeting.  

The navigation to the GA report is not yet ready.

**Comment by John123Yu** [comment]
@JJediny @kvuppala @hkdctol @philipashlock

The latest changes, including adding metrics sub-navigation bar is now on the Metrics Page, Full History Page, and Site Usage page for BSP DEV and OSCIT http://34.226.152.211/site-usage . We modified the sidebar for Site-usage page to be like the side bar on the resources page, making the theming more consistent.

**Comment by John123Yu** [comment]
@JJediny @hkdctol @philipashlock @kvuppala 

This has been pushed to production. 

https://catalog-bsp.data.gov/site-usage

Currently we are downloading all the GA data dating back to July 2014. I will inform when all the data has been downloaded.
